<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
use PHPMailer\PHPMailer\SMTP;

session_start();
$dbconn = include '_layout/_dbconnection.php';
if ($dbconn) {}else{ header("Location: 404");}
    
if (isset($_POST['submit'])){
    
    require '_mailer/PHPMailer.php';
    require '_mailer/SMTP.php';
    require '_mailer/Exception.php';
    
    $name = "Mheed";
    $email = "etiketochukwu@gmail.com";
    $msg = "test".$email."test <?php echo ".$email."; ?>";

    $mail = new PHPMailer();
    $mail->isSMTP();
    $mail->Host = 'mail.tedmaniatv.com';
    $mail->SMTPAuth = true;
    $mail->Username = 'admin@tedmaniatv.com'; //paste one generated by Mailtrap
    $mail->Password = '@lhZkJC_9*p{'; //paste one generated by Mailtrap
    $mail->SMTPSecure = 'ssl';
    $mail->Port = 465;
    
    $mail->setFrom($email, 'User');
    $mail->addReplyTo($email, 'Mailtrap');
    $mail->addAddress('etiketochukwusamuel@gmail.com', 'Mheed'); # name is optional
    #$mail->addCC('info@tedmaniatv.com', 'Elena');
    #$mail->addBCC('etiketochukwu@gmail.com', 'Alex');
    
    $mail->Subject = 'Test Email via Mailtrap SMTP using PHPMailer';
    $mail->isHTML(true);
    # $mailContent = "<h1>Send HTML Email using SMTP in PHP</h1>
    #<p>This is a test email I’m sending using SMTP mail server with PHPMailer.</p>";
    $mail->Body = $msg;
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
    
    if($mail->send()){
        echo 'Message has been sent';
    }else{ 
        echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
    }
}

?>

<!DOCTYPE html>
<html>
<head>
<title>Mail</title>

<!-- CSS Libraries -->
<link rel="stylesheet" href="assets/modules/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="assets/modules/fontawesome/css/all.min.css">
<link rel="stylesheet" href="assets/fonts/font-awesome-6/css/all.css">

<!-- Template CSS -->
<link rel="stylesheet" href="assets/css/style.min.css">
<link rel="stylesheet" href="assets/css/components.min.css">
<link rel="stylesheet" href="assets/css/mystyle.css">
<link rel="stylesheet" href="assets/css/mails.css">
</head>
<body>
    <div class="content bg-light">
        <div class="logo">
            <img src="assets/img/example-image.jpg" width="70" height="70">
            <span>SimGanic</span>
        </div>
        <div class="content-body">
            <h5 class="content-header-text">Welcome, $Firstname!</h5>
            <h6>You’re Almost There,</h6>
            <div>An account was just created at <a href="">simganic.com</a> with this email address. Before we proceed, we need to confirm this request came from you, so if it did then kindly click the link below to confirm your account.</div>
            <a href="" class="btn btn-primary">Confirm My Account <i class="fa fa-arrow-right"></i></a>
            <div>Please note that unverified accounts are <strong>automatically deleted</strong> 30days after sign up.</div>
            <strong>PS:</strong> if you didn't sign up at <a href="">simganic.com</a>, send a report to <a href="">reports@simganic.com</a> to block the account.
            <hr>
            <div class="text-right">
                <div>Thanks,</div>
                <a href="">support@simganic.com</a>
                <div class="content-footer">
                <a href=""><i class="fa-brands fa-facebook"></i></a> 
                <a href=""><i class="fa-brands fa-whatsapp"></i></a> 
                <a href=""><i class="fa-brands fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="content bg-light">
        <div class="logo">
            
        </div>
        <div class="content-body">
            <?php
                # working cos of session start and db connection above
                $id = '340441424';
                $_user_email_address = $_SESSION['email'];
                $page_link = "https://simganic.com/shipped-products?order-id=".$id;
                $pre_link = "https://simganic.com/products/";
                $faq_link = "https://simganic.com/faqs#cancel-order";
                
                $GetCartDetails = $SingleOrders = "SELECT * FROM _allorders WHERE crc32(invoice) = '$id' AND email = '$_user_email_address' AND status != 'Closed'";
                $GetCartDetailsResult = $con->query($GetCartDetails);
                $rowcount = mysqli_num_rows($GetCartDetailsResult);
                //echo $rowcount."<br>";
                if ($GetCartDetailsResult->num_rows > 0) {
                    while ($cartRow = mysqli_fetch_assoc($GetCartDetailsResult)) {
                        $order_items = $cartRow["items"];
                        $order_inv = $cartRow["invoice"];
                        $order_status = ucwords($cartRow["status"]);
                        $order_total_price = $cartRow["total_price"];
                        $order_items = unserialize($order_items);     

                        include '_layout/_currency_converter.php';
                        $currency_symbol = $user_selected_currency_symbol;

                        /*switch ($order_status) {
                            case 'Paid':
                                $text = "The payment for your order has been confirmed! We'll send an alert mail when your order gets shippeed.";
                                break;
                            case 'Shipped':
                                $text = "";
                                break;
                            case 'Delivered':
                                $text = "";
                                break;
                            case 'Closed':
                                $text = "Your order ".$order_inv." has been closed. Check order details page for more information";
                                break;
                            default:
                                # code...
                                break;
                        }*/
            ?>
            <h5>Status Changed For Order: <?php echo strtoupper($order_inv);?></h5>
            <hr>
            <div>
                <p><strong>Hi <?php echo ucwords($_SESSION['lastname']); ?>,</strong></p>
                The payment for your order has been confirmed! We'll send an alert mail when your order gets shippeed. 
            </div>
            <h6 class="h6-light"><a href="<?php echo $page_link; ?>" class="btn btn-primary">Check Order Status</a></h6>
            <h6 class="h6-light" style="margin-bottom:10px;">Order Summary :</h6>
            <div class="table-responsie">
            <table class="table table-striped table-hover table-md">
                <tr>
                    <th data-width="40">#</th>
                    <th>Item(s)</th>
                    <th class="text-center">Price</th>
                    <th class="text-center">Quantity</th>
                    <th class="text-right">Total</th>
                </tr>
                <?php
                    foreach ($order_items as $key => $value) {
                        $GetProductDetails = "SELECT * FROM product_details WHERE product_id = '$value[p_id]'";
                        $GetProductDetailsResult = $con->query($GetProductDetails);
                        while ($row = mysqli_fetch_assoc($GetProductDetailsResult)) {
                            if ($GetProductDetailsResult->num_rows > 0) {
                                $name = $row["product_name"];            
                ?>
                <tr>
                    <td><strong>#</strong></td>
                    <td><?php echo $name." <strong>(".$value['p_size'].")</strong>"; ?></td>
                    <td class="text-center"><?php echo $currency_symbol."<span class='show-bg'> </span>".$value['p_price']; ?></td>
                    <td class="text-center"><?php echo $value['p_qty']; ?></td>
                    <td class="text-right"><?php echo $currency_symbol."<span class='show-bg'> </span>".number_format((intval($value['p_price']) * intval($value['p_qty'])), 2); ?></td>
                </tr>
                <?php }}}?>
                                
            </table>
            <div class="text-right table-total">
                <div style="margin: 10px 0px !important;"><strong>SubTotal :</strong> <?php echo $currency_symbol."<span class='show-bg'> </span>".number_format($order_total_price, 2); ?></div>
                <div><strong>Total (+ Shipping Fee) :</strong> <?php echo $currency_symbol."<span class='show-bg'> </span>".number_format($order_total_price, 2); ?></div>
            </div>
            </div>
            <?php }} ?>
            <hr>
            <div>
                <strong>NOTE:</strong> Orders can only be cancelled before they get shipped to get a full refund.<br>
                Orders cancelled after shipment must be returned fully packaged and will be refunded without the shipping fee <div class="bullet"></div> <a href="<?php echo $faq_link; ?>">Read More <i class="fa fa-arrow-right"></i></a> 
            </div>
            <hr>
            <div class="text-right">
                <div>Thanks For Shopping With Us,</div>
                <a href="mailto:support@simganic.com">support@simganic.com</a>
                <div class="content-footer">
                <a href=""><i class="fa-brands fa-facebook"></i></a> 
                <a href=""><i class="fa-brands fa-whatsapp"></i></a> 
                <a href=""><i class="fa-brands fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="content bg-light">
        <div class="logo">
            
        </div>
        <div class="content-body">
            <h5 class="content-header-text">Reset You SimGanic Account Password,</h5>
            <div>A request to reset <strong>"etiketochukwu@gmail.com"</strong> <a href="">simganic</a> account password was just sent. Before we proceed, we need to confirm this request came from you, so if it did then kindly click the link below to reset your password.</div>
            <a href="" class="btn btn-primary">Reset My Password <i class="fa fa-arrow-right"></i></a>
            <div><strong>PS:</strong> if you didn't request a reset of your account password, send a report to <a href="">reports@simganic.com</a> to cancel the request.</div>
            <hr>
            <div class="text-right">
                <div>SimGanic,</div>
                <a href="">support@simganic.com</a>
                <div class="content-footer">
                <a href=""><i class="fa-brands fa-facebook"></i></a> 
                <a href=""><i class="fa-brands fa-whatsapp"></i></a> 
                <a href=""><i class="fa-brands fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="content bg-light">
        <div class="logo">
            
        </div>
        <div class="content-body">
        <?php 
            # session start and db connection above
            $id = '2505977468';
            $_user_email_address = $_SESSION['email'];
            $pre_link = "https://simganic.com/products/";
            $SingleOrders = "SELECT * FROM _allorders WHERE crc32(invoice) = '$id' AND email = '$_user_email_address' AND status != 'Closed'";
            $SingleOrdersResult = $con->query($SingleOrders);
            if ($SingleOrdersResult -> num_rows > 0) {
                while($_row = mysqli_fetch_array($SingleOrdersResult)){
                    $order_email = $_row["email"];
                    $order_name = $_row["name"];
                    $order_items = $_row["items"];
                    $order_address = $_row["address"];
                    $order_phone_number = $_row["phone_number"];
                    $order_total_price = $_row["total_price"];
                    $order_invoice = $_row["invoice"];
                    $order_shipping_fee = $_row["shipping_fee"];
                    $order_date = $_row["_date"];
                    $order_time = $_row["_time"];
                    $order_status = ucwords($_row["status"]);
                    $order_delivery_date = $_row["delivery_date"];

                    $order_items = unserialize($order_items);

                    $_user_email_address = $order_email;

                    include '_layout/_currency_converter.php';
                    if ($order_shipping_fee == null) {
                        $order_shipping_fee = 0;
                    }
    
                    $currency_symbol = $user_selected_currency_symbol;
        ?>
            <h5>Order: <?php echo strtoupper($order_invoice) ?> Delivery Confirmed</h5>
            <hr>
            <div>
                Your order: <?php echo strtoupper($order_invoice) ?> has been confirmed. You can cross-check order details below.
            </div>
            <address>
                <h6 class="">Ordered On</h6>
                <?php echo $order_date ?> 
                <div class="bullet"></div>
                <?php echo $order_time ?>                        
            </address>
            <address>
                <h6 class="">Delivered On</h6>
                <?php echo $order_delivery_date ?>                        
            </address>
            <address>
                <h6 class="">Billed To:</h6>
                <strong>Name :</strong> <?php echo $order_name;?> <div class="bullet"></div>
                <strong>Email Address :</strong> <?php echo $order_email; ?><br>
                <strong>Phone No :</strong> <?php echo $order_phone_number ; ?>                        
            </address>
            <address>
                <h6 class="">Shipped To:</h6>
                <?php echo $order_address ;?>
            </address>
            <h6 class="" style="margin-bottom:10px;margin-top:10px;">Order Summary :</h6>

            <table class="table table-striped table-hover table-md">
                <tr>
                    <th data-width="40">#</th>
                    <th>Product(s)</th>
                    <th class="text-center">Price</th>
                    <th class="text-center">Quantity</th>
                    <th class="text-right show-bg">Total</th>
                </tr>
                <?php
                    foreach ($order_items as $key => $value) {
                        $GetProductDetails = "SELECT * FROM product_details WHERE product_id = '$value[p_id]' ORDER BY product_no_reviews DESC";
                        $GetProductDetailsResult = $con->query($GetProductDetails);
                        while ($row = mysqli_fetch_assoc($GetProductDetailsResult)) {
                            if ($GetProductDetailsResult->num_rows > 0) {
                                $name = $row["product_name"];  
                                $link = $row["product_link"];            
                ?>
                <tr>
                    <td><strong>#</strong></td>
                    <td><a href="<?php echo $pre_link.$link?>/"><?php echo $name." (".$value['p_size'].")"; ?></a></td>
                    <td class="text-center"><?php echo $currency_symbol."<span class='show-bg'> </span>".$value['p_price']; ?></td>
                    <td class="text-center"><?php echo $value['p_qty']; ?></td>
                    <td class="text-right show-bg"><?php echo $currency_symbol."<span class='show-bg'> </span>".number_format((intval($value['p_price']) * intval($value['p_qty'])), 2); ?></td>
                </tr>
                <?php }}}?>
            </table>
        <?php }} ?>

            <div class="text-right table-total">
                <div><strong>SubTotal:</strong> <?php echo $currency_symbol."<span class='show-bg'> </span>".number_format($order_total_price, 2); ?></div>
                <div><strong>Total (+ Shipping Fee) :</strong> <?php echo $currency_symbol."<span class='show-bg'> </span>".number_format(($order_total_price + $order_shipping_fee), 2); ?></div>
            </div>
            <hr>
            <div>
                How was your shopping experience? We rely on customer reviews to help shoppers learn more abut our products. You can share a thought by adding a star rating and comment <div class="bullet"></div> <a href="<?php echo $pre_link.$link; ?>/">Submit A Review <i class="fa fa-arrow-right"></i>
            </div>
            <hr>
            <div class="text-right" style="margin-top:40px;">
                <div>Thanks For Shopping With Us,</div>
                <a href="mailto:support@simganic.com">support@simganic.com</a>
                <div class="content-footer">
                <a href=""><i class="fa-brands fa-facebook"></i></a> 
                <a href=""><i class="fa-brands fa-whatsapp"></i></a> 
                <a href=""><i class="fa-brands fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>