<?php
    session_start();
    
    $dbconn = include '_layout/_dbconnection.php';
    if ($dbconn) {}else{ header("Location: 404");}

    require '_layout/_time_ago.php';

    $message = [];
    $messages = [];

    if (!isset($_SESSION['loggedin'])) {
        header('Location: sign-in?redirect=disputes');    
    }else{
        $_user_email_address = $_SESSION['email'];
        $_user_name = $_SESSION['username'];
    }

    use PHPMailer\PHPMailer\PHPMailer;
    use PHPMailer\PHPMailer\Exception;
    use PHPMailer\PHPMailer\SMTP;

    if (isset($_POST["confirm-order"])) {
        $order = trim(strip_tags(htmlspecialchars($_POST["inv"])));
        $CheckIfOrderExist = "SELECT * FROM _allorders WHERE crc32(invoice) = '$order' AND email = '$_user_email_address' AND status = 'Delivered'";
        $OrderExist = $con->query($CheckIfOrderExist);
        if ($OrderExist->num_rows > 0) {
            $row = mysqli_fetch_array($OrderExist);
            $_inv = $row["invoice"];
            $date = date("F jS, Y");
            $Dismissps = "UPDATE _allorders SET status = 'Closed', updated_on = '$date' WHERE invoice = '$_inv' AND email = '$_user_email_address' AND status = 'Delivered'";
            $DismisspsResult = $con->query($Dismissps);
            if ($DismisspsResult) {
                array_push($messages, "Order With Invoice: ".$order." Closed Succesfully.");
                # send mail
                # send mail
                require '_mailer/PHPMailer.php';
                require '_mailer/SMTP.php';
                require '_mailer/Exception.php';
                            
                $mail = new PHPMailer();
                $mail->isSMTP();
                $mail->Host = 'mail.tedmaniatv.com'; # prolly use simganic smtp
                $mail->SMTPAuth = true;
                $mail->Username = 'admin@tedmaniatv.com'; # paste one generated by Mailtrap
                $mail->Password = '@lhZkJC_9*p{'; # paste one generated by Mailtrap
                $mail->SMTPSecure = 'ssl';
                $mail->Port = 465;

                $id = $order;
                $page_link = "https://simganic.com/shipped-products?order-id=".$id;
                $pre_link = "https://simganic.com/products/";
                $faq_link = "https://simganic.com/faqs#cancel-order";
                $web = "https://simganic.com/";
                $website = "https://simganic.com/";
                $report_link = "https://simganic.com/report-order?order=".$id;

                $mail->setFrom("support@simganic.com", "SimGanic");
                $mail->addReplyTo("support@simganic.com", "SimGanic");
                $mail->addAddress($_user_email_address); # name is optional

                $mail->Subject = "Order: ".strtoupper($_inv)." Delivery Confirmed";
                $mail->isHTML(true);
                
                $user_confirmed_order_delivered_email = '
                    <!DOCTYPE html>
                    <html>
                    <head>
                    </head>
                    <body>
                        <div class="content bg-light" style="color:#563d7c;border: 1px solid #563d7c;padding: 10px;border-radius: 5px;background-color:#DCE1E5 !important;font-family: \'Raleway\', \'Segoe UI\', arial;font-size:15px;">
                            <div class="logo">
                                
                            </div>
                            <div class="content-body" style="background: white;padding: 20px;border-radius: 5px;">
                            '; 
                                # session start and db connection above
                                $SingleOrders = "SELECT * FROM _allorders WHERE crc32(invoice) = '$id' AND email = '$_user_email_address' AND status != 'Closed'";
                                $SingleOrdersResult = $con->query($SingleOrders);
                                if ($SingleOrdersResult -> num_rows > 0) {
                                    while($_row = mysqli_fetch_array($SingleOrdersResult)){
                                        $order_email = $_row["email"];
                                        $order_name = $_row["name"];
                                        $order_items = $_row["items"];
                                        $order_address = $_row["address"];
                                        $order_phone_number = $_row["phone_number"];
                                        $order_total_price = $_row["total_price"];
                                        $order_invoice = $_row["invoice"];
                                        $order_shipping_fee = $_row["shipping_fee"];
                                        $order_date = $_row["_date"];
                                        $order_time = $_row["_time"];
                                        $order_status = ucwords($_row["status"]);
                                        $order_delivery_date = $_row["delivery_date"];

                                        $order_items = unserialize($order_items);

                                        $_user_email_address = $order_email;

                                        include "_layout/_currency_converter.php";
                                        if ($order_shipping_fee == null) {
                                            $order_shipping_fee = 0;
                                        }
                                        if ($_SESSION['lastname'] != null) {$_usr = $_SESSION['lastname'];}else{$_usr = $_SESSION['username'];}
                                        $currency_symbol = $user_selected_currency_symbol;
                            $user_confirmed_order_delivered_email .= '
                                <div class="content-header-text" style="font-weight:700;margin-bottom: 10px;font-size:25px;">
                                Order: '.strtoupper($order_invoice).' Delivery Confirmed</div>
                                <hr style="margin-bottom:20px;">
                                <div style="font-size:17px;">
                                	<div style="display:none;">Hi '.ucwords($_usr).',</div>
                                    Your order: '.strtoupper($order_invoice).' has been confirmed. You can cross-check order details below.
                                </div>
                                <address style="font-style:normal !important;margin-top:30px;">
                                    <div class="" style="font-weight:700;font-size:17px;margin-bottom:10px;text-decoration:none;">Ordered On</div>
                                    '.$order_date.' 
                                    <div class="bullet" style="margin:5px;"></div>
                                    '.$order_time.'                        
                                </address>
                                <address style="font-style:normal !important;margin-top:30px;">
                                    <div class="" style="font-weight:700;font-size:17px;margin-bottom:10px;text-decoration:none;">Delivered On</div>
                                    '.$order_delivery_date.'                        
                                </address>
                                <address style="font-style:normal !important;margin-top:30px;">
                                    <div class="" style="font-weight:700;font-size:17px;margin-bottom:10px;text-decoration:none;">Billed To:</div>
                                    <div><strong>Name :</strong> '.ucwords($order_name).' </div>
                                    <div style="margin-top:5px;"><strong>Email Address :</strong> '.$order_email.'</div>
                                    <div style="margin-top:5px;"><strong>Phone No :</strong> '.$order_phone_number.' </div>                       
                                </address>
                                <address style="font-style:normal !important;margin-top:30px;">
                                    <div class="" style="font-weight:700;font-size:17px;margin-bottom:10px;text-decoration:none;">Shipped To:</div>
                                    '.$order_address.'
                                </address>
                                <div style="font-weight:700;font-size:17px;margin-bottom:15px;margin-top:30px;">Order Summary :</div>

                                <table class="table table-striped table-hover table-md" style="width:100%;color:#563d7c;border: 1px solid #563d7c;border-collapse: collapse;">
                                    <tr>
                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;">#</th>
                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:left;">Product(s)</th>
                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:center;">Price</th>
                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:center;">Quantity</th>
                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:right;">Total</th>
                                    </tr>
                                    ';
                                        foreach ($order_items as $key => $value) {
                                            $val = $value['p_id'];
                                            $GetProductDetails = "SELECT * FROM product_details WHERE product_id = '$val'";
                                            $GetProductDetailsResult = $con->query($GetProductDetails);
                                            while ($row = mysqli_fetch_assoc($GetProductDetailsResult)) {
                                                if ($GetProductDetailsResult->num_rows > 0) {
                                                    $name = $row["product_name"];  
                                                    $link = $row["product_link"];            
                                    $user_confirmed_order_delivered_email .= '
                                    <tr>
                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:center;"><strong>#</strong></td>
                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:left;"><a style="text-decoration:none;" href="'.$pre_link.$link.'/">'.$name.' ('.$value['p_size'].')</a></td>
                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:center;">'.$currency_symbol."".$value['p_price'].'</td>
                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:center;">'.$value['p_qty'].'</td>
                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:right;">'.$currency_symbol."".number_format((intval($value['p_price']) * intval($value['p_qty'])), 2).'</td>
                                    </tr>
                                    '; }}} $user_confirmed_order_delivered_email .= '
                                </table>
                            '; }} $user_confirmed_order_delivered_email .= '

                                <div class="text-right table-total" style="text-align:right;">
                                    <div style="margin: 10px 0px !important;"><strong>SubTotal :</strong> '.$currency_symbol."<span class='show-bg'> </span>".number_format($order_total_price, 2).'</div>
                                    <div><strong>Total (+ Shipping Fee) :</strong> '.$currency_symbol."<span class='show-bg'> </span>".number_format(($order_total_price + $order_shipping_fee), 2).'</div>
                                </div>
                                <div style="margin-top:20px;margin-bottom:20px;">
                                    How was your shopping experience? We rely on customer reviews to help shoppers learn more abut our products. You can share a thought by adding a star rating and comment. 
                                    <div style="margin-top:20px;margin-bottom:20px;">
                                    <a href="'.$pre_link.$link.'/" style="text-align: center;box-shadow:0 2px 6px #7a58ad;background-color:#563d7c;border-color:#563d7c;padding: 10px 10px;color:white;text-decoration:none;border-radius:5px;">
                                    Submit A Review &raquo;
                                    </a>
                                    </div>
                                </div>
                                <hr>
                                <div class="text-right" style="text-align:right;margin-top:40px;">
                                    <div>Thanks For Shopping With Us,</div>
                                    <a href="mailto:support@simganic.com" style="text-decoration:none;">support@simganic.com</a>
                                    <div class="content-footer">
                                    <a href=""><i class="fa-brands fa-facebook"></i></a> 
                                    <a href=""><i class="fa-brands fa-whatsapp"></i></a> 
                                    <a href=""><i class="fa-brands fa-instagram"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </body>
                    </html>
                '; # send invoice
                $mail->Body = $user_confirmed_order_delivered_email; # order invoice
                $mail->AltBody = "Order: ".strtoupper($_inv)." Delivery Confirmed";

                $mail->send();
                if($mail->send()){
                    header("Location: shipped-products");
                }else{ 
                    array_push($messages, "<i class='fa fa-cancel'></i> Error 501! Status Update Mail Not Sent. Mailer Error: {$mail->ErrorInfo}");
                    # header("redirect: 4;url=shipped-products");
                }
            }else{
                array_push($messages, "<i class='fa fa-cancel'></i> Error 501! Order Update Error.");
            }
        }else{
            array_push($messages, "<i class='fa fa-cancel'></i> Error 402 Invoice Error! Refrain From Switching Order Invoice Values To Avoid Getting Banned On SimGanic");
        }
    }

    if (isset($_POST["submit"])) {
        $mssge = trim($_POST["reply"]);
        $reply_id = trim($_POST["reply_id"]);
        $reply_email = trim($_POST["reply_email"]);

        $mssge = str_replace( '<p>' , '%p%', $mssge );
        $mssge = str_replace( '</p>', '%/p%', $mssge );
        $mssge = str_replace( '<b>' , '%b%', $mssge );
        $mssge = str_replace( '</b>', '%/b%', $mssge );
        $mssge = str_replace( '<u>' , '%u%', $mssge );
        $mssge = str_replace( '</u>', '%/u%', $mssge );
        $mssge = str_replace( '\'' , '"', $mssge );
        $mssge = str_replace( '\\' , '%\\%', $mssge );
        $mssge = htmlentities($mssge );
        
        $mssge = strip_tags($mssge);
        $reply_id = strip_tags(htmlentities($reply_id));
        $reply_email = strip_tags(htmlspecialchars($reply_email));

        if ($_SESSION['lastname'] != null && $_SESSION['firstname'] != null) {
            $usr = $_SESSION['firstname'].' '.$_SESSION['lastname'];
        }else{
            $usr = $_SESSION['username'];
        }
        
        $SingleOrders = "SELECT * FROM _disputes WHERE crc32(dispute_id) = '$reply_id' AND dispute_email = '$reply_email' AND status != 'Closed'";
        $SingleOrdersResult = $con->query($SingleOrders);
        if ($SingleOrdersResult -> num_rows > 0) {
            while($_row = mysqli_fetch_array($SingleOrdersResult)){
                $replies = $_row["dispute_reply"];

                $replies = unserialize($replies);
                $randId = crc32($mssge).uniqid();
                $newreply = array(array(
                            'id' => $randId, 
                            'name' => $usr, 
                            'role' => 'Customer', 
                            'message' => $mssge,
                ));
                $inputed_reply = array_merge($replies, $newreply);
                $inputed_reply = serialize($inputed_reply);
                $DismissDisputes = "UPDATE _disputes SET dispute_reply = '$inputed_reply' WHERE crc32(dispute_id) = '$reply_id' AND dispute_email = '$reply_email' AND status != 'Closed'";
                $DismissDisputesResult = $con->query($DismissDisputes);
                if ($DismissDisputesResult) {
                    array_push($message, "Dispute Follow Up Updated Succesfully.");
                }else{
                    array_push($message, "Unsuccessful: {$con->error}");
                }
            }
        }
        

        # var_dump($arr);
    }
?>
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
<title>Open Disputes - SimGanic</title>

<!-- General CSS Files -->
<link rel="stylesheet" href="assets/modules/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="assets/modules/fontawesome/css/all.min.css">
<link rel="stylesheet" href="assets/fonts/font-awesome-6/css/all.css">

<!-- CSS Libraries -->
<link rel="stylesheet" href="assets/modules/summernote/summernote-bs4.css">

<!-- Template CSS -->
<link rel="stylesheet" href="assets/css/style.min.css">
<link rel="stylesheet" href="assets/css/components.min.css">
<link rel="stylesheet" href="assets/css/mystyle.css">
<link rel="stylesheet" href="assets/css/trck.css">
</head>

<body class="layout-1">
<!-- Page Loader -->
<div class="page-loader-wrapper">
    <span class="loader"><span class="loader-inner"></span></span>
</div>

<div id="app">
    <div class="main-wrapper main-wrapper-1">
        <div class="navbar-bg"></div>
        
        <?php include '_layout/_header_sidebar.php';?>
        
        <!-- Start app main Content -->
        <div class="main-content">
            <section class="section">
                <div class="section-header">
                    <div class="section-header-breadcrumb">
                        <div class="breadcrumb-item active"><a href="/">Home</a></div>
                        <div class="breadcrumb-item">Open Disputes</div>
                    </div>
                </div>

                <div class="section-body">
                    <?php if (count($messages) > 0) : ?>
                        <div class="alert-div">
                            <?php foreach ($messages as $error) : ?>
                            <div class="alert alert-primary alert-dismissible show fade">
                                <div class="alert-body">
                                    <button class="close" data-dismiss="alert"><span>×</span></button>
                                    <?php echo $error ?>
                                </div>
                            </div>
                            <?php endforeach ?>
                        </div>
                    <?php endif ?>

                    <?php 
                        if (isset($_GET["dispute-id"])) {
                            $id = trim(strip_tags($_GET["dispute-id"]));
                            $SingleDisputes = "SELECT * FROM _disputes WHERE crc32(dispute_id) = '$id' AND dispute_email = '$_user_email_address' AND status != 'Closed'";
                            $SingleDisputesResult = $con->query($SingleDisputes);
                            if ($SingleDisputesResult -> num_rows > 0) {
                    ?>
                    <div class="w-100" style="text-align:right;">
                        <form>
                            <input type="hidden" value="<?php echo $dispute_id; ?>" name="c_id">
                            <button class="btn btn-danger" name="close-dispute-btn"><i class="fa fa-close"></i> Close Dispute</button>
                        </form>
                    </div><br>
                    <?php
                                while($_row = mysqli_fetch_array($SingleDisputesResult)){
                                    $dispute_email = $_row["dispute_email"];
                                    $dispute_id = $_row["dispute_id"];
                                    $dispute_category = $_row["dispute_category"];
                                    $dispute_header = $_row["dispute_header"];
                                    $dispute_message = $_row["dispute_message"];
                                    
                                    $dispute_message = str_replace( '%p%' , '<p>', $dispute_message );
                                    $dispute_message = str_replace( '%/p%', '</p>', $dispute_message);
                                    $dispute_message = str_replace( '%b%' , '<b>', $dispute_message );
                                    $dispute_message = str_replace( '%/b%', '</b>', $dispute_message );
                                    $dispute_message = str_replace( '%u%' , '<u>', $dispute_message );
                                    $dispute_message = str_replace( '%/u%', '</u>', $dispute_message );
                                    $dispute_message = str_replace( '%\\%', '\\', $dispute_message );
                                    $dispute_message = str_replace( 'font-size' , 'f', $dispute_message );
                                    $dispute_message = str_replace( 'font-family' , 'f', $dispute_message );
                                    $dispute_message = str_replace( 'h3' , 'b', $dispute_message );
                                    
                                    $dispute_status = ucwords($_row["status"]);
                                    $date = ucwords($_row["timestamp"]);
                                    
                                    switch (ucwords($dispute_status)) {
                                        case 'Active':
                                            $btn_class = "btn btn-danger";
                                            $updateStatus = "Cancelled";
                                            break;

                                        case 'Open':
                                            $btn_class = "btn btn-light";
                                            $updateStatus = "Shipped";
                                            break;

                                        case 'Closed':
                                            $btn_class = "btn btn-warning";
                                            $updateStatus = "Delivered";
                                            break;

                                        default:
                                            $btn_class = "btn btn-primary";
                                            $updateStatus = "Shipped";
                                            break;
                                    }

                                    $_user_email_address = $dispute_email;

                                    include '_layout/_currency_converter.php';
    
                                    $currency_symbol = $user_selected_currency_symbol;
                    ?>
                    <div class="col-md-12">
                        <div class="tickets">
                            <div class="ticket-content" style="width:100% !important;">
                                <div class="ticket-header">
                                    <div class="ticket-sender-picture img-shadow"><img src="assets/img/avatar/avatar.jpg" alt="image"></div>
                                    <div class="ticket-detail">
                                        <div class="ticket-title">
                                            <h4><?php echo $dispute_header; ?></h4>
                                        </div>
                                        <div class="ticket-info">
                                            <div class="font-weight-600 show-bg"><?php echo ucwords(str_replace("-"," ",$dispute_category)); ?></div>
                                            <div class="bullet show-bg"></div>
                                            <div class="font-weight-600"><?php echo $dispute_email; ?></div>
                                            <div class="bullet"></div>
                                            <div class="text-primary font-weight-600"><div class="text-primary"><?php echo TimeAgo($date, date("Y-m-d H:i:s")); ?></div></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="ticket-description">
                                    <p><?php echo $dispute_message; ?></p>
                                    <div>
                                        <strong>Status <div class="bullet"></div> <button class="close-d <?php echo $btn_class; ?>" type="button"> <?php echo $dispute_status;?></button></strong>
                                    </div><br>
                                    <div class="ticket-divider"></div>
                                    <?php
                                        $ReplyDisputes = "SELECT * FROM _disputes WHERE dispute_id = '$dispute_id' AND dispute_reply != 'a:0:{}'";
                                        $ReplyDisputesResult = $con->query($ReplyDisputes);
                                        if ($ReplyDisputesResult -> num_rows > 0) { ?>
                                            <div style="margin-bottom:10px;margin-top:10px;"><h5><i class="fa fa-hashtag"></i> Disputes Follow Up</h5></div><hr>
                                        <?php
                                            while($_row = mysqli_fetch_array($ReplyDisputesResult)){
                                                $replies = $_row["dispute_reply"];
                                                if ($replies == null) {
                                                    $replies = [];
                                                    $replies = serialize($replies);
                                                }else{

                                                }
                                                $replies = unserialize($replies);
                                                
                                                $cnt = count($replies);
                                                foreach ($replies as $key => $reply) {
                                                    $reply['message'] = str_replace( '%p%' , '<p>', $reply['message'] );
                                                    $reply['message'] = str_replace( '%/p%', '</p>', $reply['message']);
                                                    $reply['message'] = str_replace( '%b%' , '<b>', $reply['message'] );
                                                    $reply['message'] = str_replace( '%/b%', '</b>', $reply['message'] );
                                                    $reply['message'] = str_replace( '%u%' , '<u>', $reply['message'] );
                                                    $reply['message'] = str_replace( '%/u%', '</u>', $reply['message'] );
                                                    $reply['message'] = str_replace( '%\\%', '\\', $reply['message'] );
                                                    $reply['message'] = str_replace( 'font-size' , 'f', $reply['message'] );
                                                    $reply['message'] = str_replace( 'font-family' , 'f', $reply['message'] );
                                                    $reply['message'] = str_replace( 'h3' , 'b', $reply['message'] );
                                    ?>
                                    <div class="tickets" style="margin-bottom: -25px !important;">
                                        <div class="ticket-content" style="width:100% !important;">
                                            <div class="ticket-header">
                                                <div class="ticket-sender-picture img-shadow" style="width:30px !important;height:30px !important;"><img src="assets/img/avatar/avatar.jpg" alt="image" width="30" height="30"></div>
                                                <div class="ticket-detail">
                                                    <div class="ticket-title">
                                                        <h6 style="margin-bottom: -5px !important;"><?php echo ucwords($reply['name']);?></h6>
                                                    </div>
                                                    <div class="ticket-info">
                                                        <span class="font-weight-100" style="font-size:11px !important;">
                                                            <?php echo $reply['role'];?>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="ticket-description" style="margin-top: 10px !important;font-size: 14px !important;">
                                                <?php echo html_entity_decode($reply['message']);?>
                                            </div>
                                        </div>
                                    </div><hr>
                                    <?php }}} ?>

                                    <div class="ticket-form">
                                        <form action="" method="post">
                                            <div class="form-group">
                                            <input type="hidden" value="<?php echo crc32($dispute_id); ?>" name="reply_id">
                                            <input type="hidden" value="<?php echo $dispute_email; ?>" name="reply_email">
                                            <textarea class="summernote-simple form-control" placeholder="Type a reply ..." name="reply"></textarea>
                                            </div>
                                            <div class="form-group text-right">
                                            <button class="btn btn-primary btn-icon" name="submit"><i class="fa fa-pen"></i> Reply</button>
                                            <div class="bullet"></div>
                                            <button class="btn btn-danger btn-icon" name="close-dispute-btn"><i class="fa fa-close"></i> Close Dispute</button>
                                            </div>
                                        </form>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php }}else{echo "<script>alert('Error 402! Dispute ID Error.')</script><div class='col-12 w_main'><center><div class='w_icon'><i class='fa fa-cancel' style='transform:none !important;'></i></div><br><h3>Oops!! Nothing To Show Here.</h3><p></p><a href='all-products' class='csp'><button class='btn btn-primary btn-update-s'><i class='fa fa-arrow-left'></i> Continue Shopping</button></a></center></div>";}}else{ ?>
                    <div class="w-100">
                        <?php
                            $AllDisputes = "SELECT * FROM _disputes WHERE dispute_email = '$_user_email_address' AND status = 'open' OR dispute_email = '$_user_email_address' AND status = 'active'";
                            $AllDisputesResult = $con->query($AllDisputes);
                            if ($AllDisputesResult -> num_rows > 0) { 
                        ?>
                        <div class="card">
                            <div class="card-hader" style="padding:20px 0px 0px 15px;">
                                <h4 style="font-size:18px !important;text-transform:uppercase;">Recent Disputes</h4>
                            </div><br>
                            <div class="card-body p-0">
                                <div class="table-responsve">
                                    <table class="table table-striped table-md">
                                    <tbody><tr>
                                        <th style="text-transform:uppercase;"><span class="show-bg">Dispute</span> ID</th>
                                        <th style="text-transform:uppercase;" class="text-center"><span class="show-bg">Dispute</span> Status</th>
                                        <th style="text-transform:uppercase;" class="text-center"><span class="show-bg">Dispute</span> Date</th>
                                        <th style="text-transform:uppercase;" class="text-right"><span class="show-bg">Dispute</span> Details</th>
                                    </tr>
                                    <?php
                                            while($row = mysqli_fetch_array($AllDisputesResult)){
                                                $id = $row["dispute_id"];
                                                $email = $row["dispute_email"];
                                                //$items = $row["items"];
                                                $date = $row["timestamp"];
                                                $status = ucwords($row["status"]);

                                                switch (ucwords($status)) {
                                                    case 'Active':
                                                        $btn_class = "btn-warning";
                                                        break;

                                                    case 'Closed':
                                                        $btn_class = "btn-danger";
                                                        break;

                                                    case 'Open':
                                                        $btn_class = "btn-success";
                                                        break;

                                                    default:
                                                        $btn_class = "btn-primary";
                                                        break;
                                                }
                                    ?>
                                    <tr>
                                        <td><a href="?dispute-id=<?php echo crc32($id); ?>"><?php echo '<span class="show-bg">'.$id.'</span><span class="show-sm">'.wordwrap($id,4," ",TRUE).'</span>'; ?></a></td>
                                        <td class="text-center"><div class="btn btn-status <?php echo $btn_class; ?>"><?php echo ucwords($status); ?></div></td>
                                        <td class="text-center"><?php echo $date; ?></td>
                                        <td class="text-right">
                                        <a href="?dispute-id=<?php echo crc32($id); ?>" target="_blank" class="btn btn-status btn-primary">Details <i class="fas fa-arrow-right"></i></a>
                                        </td>
                                    </tr>

                                    <?php } ?></tbody></table><?php }else{ ?>
                                    <div class="col-12 w_main">
                                        <center>
                                            <div class="w_icon">
                                                <i class="fa fa-shipping-fast" style="transform:none !important;"></i>
                                            </div> <br>
                                            <h5>You have no open or active dispute!</h5>
                                            <p>Do you have a complaint about an order or a product, click the button below to open a dispute now.</p>
                                            <a href="open-dispute" class="csp"><button class="btn btn-primary"><i class="fa fa-arrow-left"></i> Open Dispute</button></a>
                                        </center> 
                                    </div>
                                    <?php } ?>
                                    
                                    <div style="margin-left:25px;margin-bottom:10px;display:none;">
                                        Showing <strong>1 - 10</strong> of <strong>10</strong> orders <div class="bullet"></div> <a href="#" class="btn btn-danger">View All <i class="fas fa-chevron-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php } ?>
                </div>

            </section>
        </div>

        <style>
            .table.table-bordered td, .table.table-bordered th{
                border: 1px solid #dee2e6 !important;
            }
            .btn-status{
                text-transform: uppercase;
                font-weight: bolder;
                letter-spacing: 1px;
            }
            .table-total{
                border: 1px solid rgba(0,0,0,0.02) !important;
                background-color: rgba(0,0,0,0.02);
                padding: 15px;
                margin-top: -15px;
            }
            .status{
                font-weight: normal;
            }
            .btn.btn-success.btn-icon{

            }
        </style>

        <!-- Start app Footer part -->
        <?php include '_layout/_footer.php';?>
    </div>
</div>

<!-- General JS Scripts -->
<script src="assets/bundles/lib.vendor.bundle.js"></script>
<script src="js/CodiePie.js"></script>

<!-- JS Libraies -->
<script src="assets/modules/summernote/summernote-bs4.js"></script>

<!-- Page Specific JS File -->
<script>

</script>
<!-- Template JS File -->
<script src="js/scripts.js"></script>
<script src="js/custom.js"></script>
</body>

</html>