<?php
    session_start();
    
    use PHPMailer\PHPMailer\PHPMailer;
    use PHPMailer\PHPMailer\Exception;
    use PHPMailer\PHPMailer\SMTP;

    if (!isset($_SESSION['loggedin'])) {
        $_user_email_address = "";
    }else{
        $_user_email_address = $_SESSION['email'];
    }

    $dbconn = include '_layout/_dbconnection.php';
    if ($dbconn) {}else{ header("Location: 404");}

    $message = [];

    if (isset($_POST["submit-dispute"])) {
        if ($_POST["email"] !== null && $_POST["category"] !== null && $_POST["message"] !== null) {
            $id = strtoupper("#ID-".bin2hex(random_bytes(4)).mt_rand(0000,9999));
            $email = strip_tags(trim(htmlentities($_POST["email"])));
            $category = strip_tags(trim(htmlentities($_POST["category"])));
            $subject = strip_tags(trim(htmlentities($_POST["subject"])));
            if($subject == null){
                $subject = "Dispute Opened: ".$id;
            }
            $d_message = trim($_POST["message"]);
            
            $d_message = str_replace( '<p>' , '%p%', $d_message );
            $d_message = str_replace( '</p>', '%/p%', $d_message );
            $d_message = str_replace( '<b>' , '%b%', $d_message );
            $d_message = str_replace( '</b>', '%/b%', $d_message );
            $d_message = str_replace( '<u>' , '%u%', $d_message );
            $d_message = str_replace( '</u>', '%/u%', $d_message );
            $d_message = str_replace( '\'' , '"', $d_message );
            $d_message = str_replace( '\\' , '%\\%', $d_message );
            $d_message = htmlentities($d_message );
            $d_message = strip_tags($d_message);
            
            $d_reply = [];
            $d_reply = serialize($d_reply);

            $AddDispute = "INSERT INTO _disputes (dispute_id, dispute_category, dispute_email, dispute_header, dispute_message, dispute_reply, status) VALUES ('$id', '$category', '$email', '$subject', '$d_message' '$d_reply', 'open')";
            $DisputeAdded = $con->query($AddDispute);
            if ($DisputeAdded) {
                array_push($message, "Dispute Opened Submitted. SimGanic Will Contact You Via Inbox As Soon As Possible.");

                # send mail
                require '_mailer/PHPMailer.php';
                require '_mailer/SMTP.php';
                require '_mailer/Exception.php';
                            
                $mail = new PHPMailer();
                $mail->isSMTP();
                $mail->Host = 'mail.tedmaniatv.com'; # prolly use simganic smtp
                $mail->SMTPAuth = true;
                $mail->Username = 'admin@tedmaniatv.com'; # paste one generated by Mailtrap
                $mail->Password = '@lhZkJC_9*p{'; # paste one generated by Mailtrap
                $mail->SMTPSecure = 'ssl';
                $mail->Port = 465;
                
                $mail->setFrom($email);
                $mail->addReplyTo($email);
                $mail->addAddress('admin@tedmaniatv.com', 'SimGanic'); # name is optional
                
                $mail->Subject = $subject;
                $mail->isHTML(true);
                
                $mail->Body = $d_message;
                $mail->AltBody = $d_message;
                # $mail->send();
                if($mail->send()){
                    
                }else{ 
                    array_push($message, "Error 501! Dispute Mail Not Sent. Mailer Error: {$mail->ErrorInfo}");
                }
                
            }else{
                array_push($message, "Error 401! Error In Submitting Dispute.");
            }
        }else{
            array_push($message, "Error 402! Details Error");
        }
    }
?>
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
<title>Open A Dispute Ticket - SimGanic</title>

<!-- General CSS Files -->
<link rel="stylesheet" href="assets/modules/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="assets/modules/fontawesome/css/all.min.css">
<link rel="stylesheet" href="assets/fonts/font-awesome-6/css/all.css">

<!-- CSS Libraries -->
<link rel="stylesheet" href="assets/modules/select2/dist/css/select2.min.css">
<link rel="stylesheet" href="assets/modules/jquery-selectric/selectric.css">
<link rel="stylesheet" href="assets/modules/bootstrap-timepicker/css/bootstrap-timepicker.min.css">
<link rel="stylesheet" href="assets/modules/summernote/summernote-bs4.css">
<link rel="stylesheet" href="assets/modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.css">

<!-- Template CSS -->
<link rel="stylesheet" href="assets/css/style.min.css">
<link rel="stylesheet" href="assets/css/components.min.css">
<link rel="stylesheet" href="assets/css/mystyle.css">
</head>

<body class="layout-1">
<!-- Page Loader -->
<div class="page-loader-wrapper">
    <span class="loader"><span class="loader-inner"></span></span>
</div>

<div id="app">
    <div class="main-wrapper main-wrapper-1">
        <div class="navbar-bg"></div>
        
        <?php include '_layout/_header_sidebar.php';?>
        
        <!-- Start app main Content -->
        <div class="main-content">
            <section class="section">
                <div class="section-header">
                    <div class="section-header-breadcrumb"  style="margin-left:auto;">
                        <div class="breadcrumb-item active"><a href="/">Home</a></div>
                        <div class="breadcrumb-item">Open Disputes</div>
                    </div>
                </div>

                <div class="section-body">
                        <?php if (count($message) > 0) : ?>
                            <div class="alert-div">
                                <?php foreach ($message as $error) : ?>
                                <div class="alert alert-primary alert-dismissible show fade">
                                    <div class="alert-body">
                                        <button class="close" data-dismiss="alert"><span>×</span></button>
                                        <?php echo $error ?>
                                    </div>
                                </div>
                                <?php endforeach ?>
                            </div>
                        <?php endif ?>
                    <form method="POST" action="">
                        <div class="card-body pb-0">
                            <div class="form-group">
                                <label>Dispute Category:*</label>
                                <select class="form-control select2" name="category" required="">
                                    <option value="report-a-product">Report A Product</option>
                                    <option value="return-a-product">Return A Product</option>
                                    <option value="others" selected="">Others</option>
                                </select>
                            </div>

                            <div class="form-row">
                                <div class="form-group col-lg-6">
                                    <label>Email Address:*</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text">
                                                <i class="fas fa-envelope"></i>
                                            </div>
                                        </div>
                                        <input type="text" class="form-control" name="email" placeholder="Enter Email Address..." value="<?php echo $_user_email_address;?>" <?php if (isset($_SESSION['loggedin'])) { echo 'readonly=""';}else{}?>>
                                    </div>
                                </div>

                                <div class="form-group col-lg-6">
                                    <label>Dispute Subject:</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text">
                                                <i class="fas fa-pen"></i>
                                            </div>
                                        </div>
                                        <input type="text" class="form-control" name="subject" placeholder="Enter Dispute Subject...">
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label>Dispute Message:*</label>
                                <textarea class="form-control summernote-simple txt-area" name="message" placeholder="Dispute Message..." required=""></textarea>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary btn-disputes" name="submit-dispute">Submit Dispute <i class="fa fa-arrow-right"></i></button>
                            </div>
                            <style>
                                .select2-search__field{
                                    display: none !important;
                                }
                                .btn-disputes{
                                    text-transform: uppercase;
                                    letter-spacing: 1px !important;
                                }
                                .note-editable.card-block{
                                    min-height: 250px !important;
                                }
                            </style>
                        </div>
                    </form>
                </div>
            </section>
        </div>

        <!-- Start app Footer part -->
        <?php include '_layout/_footer.php';?>
    </div>
</div>

<!-- General JS Scripts -->
<script src="assets/bundles/lib.vendor.bundle.js"></script>
<script src="js/CodiePie.js"></script>

<!-- JS Libraies -->
<script src="assets/modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js"></script>
<script src="assets/modules/select2/dist/js/select2.full.min.js"></script>
<link rel="stylesheet" href="assets/modules/summernote/summernote-bs4.css">
<script src="assets/modules/jquery-selectric/jquery.selectric.min.js"></script>

<!-- Page Specific JS File -->
<script src="js/page/forms-advanced-forms.js"></script>

<!-- Template JS File -->
<script src="js/scripts.js"></script>
<script src="js/custom.js"></script>
</body>

</html>