<?php
    session_start();
    
    //dbconn
    $dbconn = include '_layout/_dbconnection.php';
    if ($dbconn) {}else{ header("Location: 404");}
    
    use PHPMailer\PHPMailer\PHPMailer;
    use PHPMailer\PHPMailer\Exception;
    use PHPMailer\PHPMailer\SMTP;

    $message = [];

    if (isset($_SESSION['loggedin'])) {
        header('Location: /');    
    }
   
    if (isset($_POST["create-account"])) {
        
            $username = "user-".mt_rand(0000000,9999999);
            $firstname = trim($_POST["firstname"]);
            $lastname = trim($_POST["lastname"]);
            $emailaddress = trim($_POST["email"]);
            $phonenumber = trim($_POST["phone"]);
            $password = trim($_POST["password"]);
            $sess_password = trim(htmlspecialchars(strip_tags($password)));
            $token = bin2hex(random_bytes(22)).mt_rand(0000000,9999999).bin2hex(random_bytes(4));

            $terms = true;
            
            $newslettter = true;
            
            # filter strings
            $firstname = htmlspecialchars(strip_tags($firstname));
            $lastname = htmlspecialchars(strip_tags($lastname));
            $emailaddress = htmlspecialchars(strip_tags($emailaddress));
            $phonenumber = htmlspecialchars(strip_tags($phonenumber));
            $password = md5(sha1(htmlspecialchars(strip_tags($password))));
            

            # activation link
            $hashedEmail = md5($emailaddress);
            $activationLink = "https://simganic.tedmaniatv.com/activate-account?e=$hashedEmail&token=$token";
            
            $CheckIfUserExist = "SELECT * FROM _users WHERE _email = '$emailaddress'";
            $UserExist = $con->query($CheckIfUserExist);
            if ($UserExist->num_rows > 0) {
                # user exist
                array_push($message, "Email Address Already Exists.");
            }else{
                # no errors add user
                $AddNewUser = "INSERT INTO _users (_firstname, _lastname, _username, _email, _phone, _password, _newsletter, _currency, _language, _token, isverified) VALUES ('$firstname', '$lastname', '$username', '$emailaddress', '$phonenumber', '$password', '$newslettter', 'NGN', 'ENG', '$token', false)";
                $UserAdded = $con->query($AddNewUser);

                if ($UserAdded) {
                    array_push($message, "Registeration Complete.");
                    # user added  
                    $usr = $firstname.' '.$lastname;
                    # send mail
                    require '_mailer/PHPMailer.php';
                    require '_mailer/SMTP.php';
                    require '_mailer/Exception.php';
                                
                    $mail = new PHPMailer();
                    $mail->isSMTP();
                    $mail->Host = 'mail.tedmaniatv.com'; # prolly use simganic smtp
                    $mail->SMTPAuth = true;
                    $mail->Username = 'admin@tedmaniatv.com'; # paste one generated by Mailtrap
                    $mail->Password = '@lhZkJC_9*p{'; # paste one generated by Mailtrap
                    $mail->SMTPSecure = 'ssl';
                    $mail->Port = 465;
                        
                    $mail->setFrom("admin@tedmaniatv.com", "SimGanic");
                    $mail->addReplyTo("admin@tedmaniatv.com", "SimGanic");
                    $mail->addAddress($emailaddress, $usr); # name is optional
                    #$mail->addCC('info@tedmaniatv.com', 'Elena');
                    #$mail->addBCC('etiketochukwu@gmail.com', 'Alex');
                    
                    $mail->Subject = "Confirm Your SimGanic Email Address";
                    $mail->isHTML(true);
                    
                    #mail dependencies
                    $web = "https://simganic.tedmaniatv.com/";
                    $confirm_email = '
                        <!DOCTYPE html>
                        <html>
                        <head>
                            <title>Mail</title>
                        </head>
                        <body>
                            <div class="content bg-light" style="border: 1px solid #563d7c;padding: 10px;border-radius: 5px;background-color:#DCE1E5 !important;font-family:Trebuchet MS;font-size:15px;">
                                <div class="logo">
                                    
                                </div>
                                <div class="content-body" style="background: white;padding: 20px;border-radius: 5px;">
                                    <div class="content-header-text" style="font-weight:700;margin-bottom: 10px;font-size:25px;">Welcome, '.ucwords($firstname).'!</div>
                                    <div style="font-weight:700;font-size:20px;margin-bottom:5px">You’re Almost There,</div>
                                    <div>An account was just created at <a href="'.$web.'" style="">simganic.com</a> with this email address. Before we proceed, we need to confirm this request came from you, so if it did then kindly click the link below to confirm your account.</div>
                                    <div style="margin-top:20px;margin-bottom:20px;"><a href="'.$activationLink.'" class="btn btn-primary" style="text-align: center;box-shadow:0 2px 6px #7a58ad;background-color:#563d7c;border-color:#563d7c;padding: 10px 10px;color:white;text-decoration:none;border-radius:5px;">
                                        Confirm My Account <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.1.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M438.6 278.6l-160 160C272.4 444.9 264.2 448 256 448s-16.38-3.125-22.62-9.375c-12.5-12.5-12.5-32.75 0-45.25L338.8 288H32C14.33 288 .0016 273.7 .0016 256S14.33 224 32 224h306.8l-105.4-105.4c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0l160 160C451.1 245.9 451.1 266.1 438.6 278.6z"/></svg>
                                    </a></div>
                                    <div style="">Please note that unverified accounts are automatically deleted 30 days after sign up.</div>
                                    if you did not sign up at <a href="'.$web.'" style="">simganic.com</a>, send a report to <a href="mailto:reports@simganic.com" style="">reports@simganic.com</a> to block the account.
                                    <hr>
                                    <div class="text-right" style="text-align:right;">
                                        <div>Welcome,</div>
                                        <a href="mailto:support@simganic.com" style="">support@simganic.com</a>
                                        <div class="content-footer">
                                        <a href=""><i class="fa-brands fa-facebook" style="font-size: 20px !important;margin: 5px;"></i></a> 
                                        <a href=""><i class="fa-brands fa-whatsapp" style="font-size: 20px !important;margin: 5px;"></i></a> 
                                        <a href=""><i class="fa-brands fa-instagram" style="font-size: 20px !important;margin: 5px;"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </body>
                        </html>
                    ';
                    $mail->Body = $confirm_email;
                    $mail->AltBody = $message;
                    
                    #$mail->send();
                    if($mail->send()){
                        array_push($message, "Login To Email Account To Confirm Your Email Address.");
                        # header('Location: /activate-account');
                        echo '<script>setTimeout(function(){ window.location.assign("activate-account") }, 3500);</script>';
                    }else{ 
                        array_push($message, "Error 501! Message could not be sent. Mailer Error: {$mail->ErrorInfo}. Contact SimGanic Admin @ <a href='mailto:support@simganic.com'>support@simganic.com</a>");
                    }

                    //$_SESSION['login_email'] = $emailaddress;
                    $_SESSION['login_password'] = $sess_password;
                    //header("Location: sign-in");
                }
            }
    }

?>
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
<title>Create Your Account - SimGanic</title>

<!-- General CSS Files -->
<link rel="stylesheet" href="assets/modules/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="assets/modules/fontawesome/css/all.min.css">
<link rel="stylesheet" href="assets/fonts/font-awesome-6/css/all.css">

<!-- CSS Libraries -->

<!-- Template CSS -->
<link rel="stylesheet" href="assets/css/style.min.css">
<link rel="stylesheet" href="assets/css/components.min.css">
<link rel="stylesheet" href="assets/css/mystyle.css">
</head>

<body class="layout-1">
<!-- Page Loader -->
<div class="page-loader-wrapper">
    <span class="loader"><span class="loader-inner"></span></span>
</div>

<div id="app">
    <div class="main-wrapper main-wrapper-1">
        <div class="navbar-bg"></div>
        
        <?php include '_layout/_header_sidebar.php';?>
        
        <!-- Start app main Content -->
        <div class="main-content">
            <section class="section">
                <div class="section-header">
                    <h1>Create Your SimGanic Account</h1>
                </div>

                <div class="section-body">
                    <div class="card" id="sample-login">
                        <form method="post" action="">
                            <div class="card-body pb-0">
                                <?php if (count($message) > 0) : ?>
                                <div class="alert-div">
                                <?php foreach ($message as $error) : ?>
                                    <div class="alert alert-primary alert-dismissible show fade">
                                        <div class="alert-body">
                                            <button class="close" data-dismiss="alert"><span>×</span></button>
                                            <?php echo $error ?>
                                        </div>
                                    </div>
                                <?php endforeach ?>
                                </div>
                                <?php endif ?>
                                <div class="form-row">
                                    <div class="form-group col-lg-6">
                                        <label>FirstName *</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">
                                                    <i class="fas fa-user"></i>
                                                </div>
                                            </div>
                                            <input type="text" class="form-control" name="firstname" placeholder="Enter FirstName" required>
                                        </div>
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label>LastName *</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">
                                                    <i class="fas fa-user"></i>
                                                </div>
                                            </div>
                                            <input type="text" class="form-control" name="lastname" placeholder="Enter LastName" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-lg-6">
                                        <label>Email Address *</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">
                                                    <i class="fas fa-envelope"></i>
                                                </div>
                                            </div>
                                            <input type="email" class="form-control" name="email" placeholder="Enter Email Address" required>
                                        </div>
                                    </div>
                                    <div class="form-group col-lg-6">
                                    <label>Phone Number *</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text">
                                                <i class="fas fa-phone"></i>
                                            </div>
                                        </div>
                                        <input type="number" class="form-control" name="phone" placeholder="Enter Phone Number..." required>
                                    </div>
                                </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-lg-6">
                                        <label>Password  *</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">
                                                    <i class="fas fa-lock"></i>
                                                </div>
                                            </div>
                                            <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password" required>
                                            <div class="input-group-append" title data-toggle="tooltip" data-placement="left" data-original-title="Toggle Password Visibility">
                                                <div class="input-group-text">
                                                    <i class="fa fa-eye eye-fa"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label>Confirm Password *</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">
                                                    <i class="fas fa-lock"></i>
                                                </div>
                                            </div>
                                            <input type="password" class="form-control" id="pass-confirm" name="confirm-password" placeholder="Confirm Password" required>
                                            <div class="input-group-append" title data-toggle="tooltip" data-placement="left" data-original-title="Toggle Password Visibility">
                                                <div class="input-group-text">
                                                    <i class="fa fa-eye eye-fa"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <input type="hidden" name="csrfToken" value="">
                                <br>
                                <label for="terms-and-pivacy-policy" style="margin-bottom:10px;">I Accept SimGanic <a href="terms-and-conditions" target="_blank">Terms and Conditions</a> &amp; <a href="privacy-policy" target="_blank">Privacy Policy</a></label>
                            </div>
                            <div class="card-footer pt-">
                                <button type="submit" name="create-account" class="btn-primary btn btn-form">Create Account</button>
                                <span class="ml-2">Already Have An Account? <a href="sign-in" class="ml-2">Login</a></span>
                                
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </div>
        <style>
            .input-group-append{
                cursor: pointer;
            }
            @media only screen and (max-width: 600px) {
                .card-footer.pt-{
                    text-align: center !important;
                }

                .btn-primary.btn.btn-form{
                    width: 100% !important;
                    margin-bottom: 10px !important;
                }
            }
        </style>

        <!-- Start app Footer part -->
        <?php include '_layout/_footer.php';?>
    </div>
</div>

<!-- General JS Scripts -->
<script src="assets/bundles/lib.vendor.bundle.js"></script>
<script src="js/CodiePie.js"></script>

<!-- JS Libraies -->

<!-- Page Specific JS File -->
<script>
    $(".input-group-append").click(function(){
        var x = document.getElementById("password");
        var y = document.getElementById("pass-confirm");
        if (x.type === "password") {
            x.type = "text";
            y.type = "text";
            $(".eye-fa").removeClass("fa-eye");
            $(".eye-fa").addClass("fa-eye-slash");
        } else {
            x.type = "password";
            y.type = "password";
            $(".eye-fa").addClass("fa-eye");
            $(".eye-fa").removeClass("fa-eye-slash");
        }
    });

    var message = $('.alert-body').text();
    var messageBox = $('.alert-div');
    if (message != "" || message != null) {
        setTimeout(hideMsg, 3000);
    }
    function hideMsg() {
        message = "";
        messageBox.fadeOut(500);
    }
</script>
<!-- Template JS File -->
<script src="js/scripts.js"></script>
<script src="js/custom.js"></script>
</body>

<!-- blank.html  Tue, 07 Jan 2020 03:35:42 GMT -->
</html>