<?php
    session_start();
    require '_layout/_dbconnection.php';
    require '_layout/_time_ago.php';
    

    $messages = [];

    use PHPMailer\PHPMailer\PHPMailer;
    use PHPMailer\PHPMailer\Exception;
    use PHPMailer\PHPMailer\SMTP;

    if (!isset($_SESSION['admin_loggedin'])) {
        header('Location: sign-in?redirect=disputes');    
    }
    
    if (isset($_POST["close-dispute-btn"])) {
        $c_dispute_id = $_POST["c_id"];

        $SearchDisputes = "SELECT * FROM _disputes WHERE dispute_id = '$c_dispute_id'";
        $SearchDisputesResult = $con->query($SearchDisputes);
        if ($SearchDisputesResult -> num_rows > 0) {
            # code...
            $DismissDisputes = "UPDATE _disputes SET status = 'closed' WHERE dispute_id = '$c_dispute_id'";
            $DismissDisputesResult = $con->query($DismissDisputes);
            if ($DismissDisputesResult) {
                array_push($messages, "Dispute Closed Succesfully.");
            }else{
                array_push($messages, "Error 401! SQL Error.");
            }
        }else{
            array_push($messages, "Error 402! Dispute ID Error.");
        }
    }

    $TotalDisputes = "SELECT * FROM _disputes WHERE status = 'open'";
    $TotalDisputesResult = $con->query($TotalDisputes);
    $disputecount = mysqli_num_rows($TotalDisputesResult);

    if (isset($_POST["submit"])) {
        $id = trim(strip_tags($_POST["id"]));
        $email = trim(strip_tags($_POST["email"]));
        $d_header = trim(strip_tags($_POST["d_header"]));
        $message = trim(strip_tags($_POST["reply"]));

        # send mail
        require '_mailer/PHPMailer.php';
        require '_mailer/SMTP.php';
        require '_mailer/Exception.php';
                    
        $mail = new PHPMailer();
        $mail->isSMTP();
        $mail->Host = 'mail.tedmaniatv.com'; # prolly use simganic smtp
        $mail->SMTPAuth = true;
        $mail->Username = 'admin@tedmaniatv.com'; # paste one generated by Mailtrap
        $mail->Password = '@lhZkJC_9*p{'; # paste one generated by Mailtrap
        $mail->SMTPSecure = 'ssl';
        $mail->Port = 465;

        $mail->setFrom("disputes@tedmaniatv.com", "SimGanic");
        $mail->addReplyTo("disputes@tedmaniatv.com", "SimGanic");
        $mail->addAddress($email); # name is optional

        $mail->Subject = "Reply To: '".ucwords($d_header)."'";
        $mail->isHTML(true);
        $mail->Body = $message;
        $UpdateDisputes = "UPDATE _disputes SET status = 'active' WHERE dispute_id = '$id'";
        $UpdateDisputesResult = $con->query($UpdateDisputes);
        if ($UpdateDisputesResult) {
            array_push($messages, "Dispute Status Updated To 'Active'.");
            if ($mail->send()) {
                array_push($messages, "Dispute Reply Sent Succesfully.");
            }else{ 
                array_push($messages, "Error 501! Message could not be sent. Mailer Error: {$mail->ErrorInfo}");
            }
        }else{
            array_push($messages, "Error 401! SQL Error.");
        }
        
    }
?>
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
<title>Resolve Disputes - SimGanic Admin</title>

<!-- General CSS Files -->
<link rel="stylesheet" href="assets/modules/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="assets/modules/fontawesome/css/all.min.css">
<link rel="stylesheet" href="assets/fonts/font-awesome-6/css/all.css">

<!-- CSS Libraries -->
<link rel="stylesheet" href="assets/modules/summernote/summernote-bs4.css">
<link rel="stylesheet" href="assets/modules/chocolat/dist/css/chocolat.css">

<!-- Template CSS -->
<link rel="stylesheet" href="assets/css/style.min.css">
<link rel="stylesheet" href="assets/css/components.min.css">
<link rel="stylesheet" href="assets/css/mystyle.css">
</head>

<body class="layout-1">
<!-- Page Loader -->
<div class="page-loader-wrapper">
    <span class="loader"><span class="loader-inner"></span></span>
</div>

<div id="app">
    <div class="main-wrapper main-wrapper-1">
        <div class="navbar-bg"></div>
        
        <?php include '_layout/_header_sidebar_admin.php';?>
        
        <!-- Start app main Content -->
        <div class="main-content">
            <section class="section">
                <div class="section-header">
                    <h1>Opened Disputes</h1>
                </div>

                <div class="section-body">
                    <?php if (count($messages) > 0) : ?>
                        <div class="alert-div">
                            <?php foreach ($messages as $error) : ?>
                            <div class="alert alert-primary alert-dismissible show fade">
                                <div class="alert-body">
                                    <button class="close" data-dismiss="alert"><span>×</span></button>
                                    <?php echo $error ?>
                                </div>
                            </div>
                            <?php endforeach ?>
                        </div>
                    <?php endif ?>
                
                    <?php 
                        if (isset($_GET["dispute-id"])) {
                            $id = trim(strip_tags($_GET["dispute-id"]));
                            $SingleDisputes = "SELECT * FROM _disputes WHERE crc32(dispute_id) = '$id'";
                            $SingleDisputesResult = $con->query($SingleDisputes);
                            if ($SingleDisputesResult -> num_rows > 0) {
                                while($_row = mysqli_fetch_array($SingleDisputesResult)){
                                    $s_disputeHeader = $_row["dispute_header"];
                                    $s_disputeId = $_row["dispute_id"];
                                    $s_disputeMessage = $_row["dispute_message"];
                                    $s_disputeEmail = $_row["dispute_email"];
                                    $s_disputeCategory = $_row["dispute_category"];
                                    $s_time = $_row["timestamp"];
                                    $s_status = $_row["status"];

                                    switch ($s_status) {
                                        case 'open':
                                            $btn_class = "btn btn-warning";
                                            break;

                                        case 'active':
                                            $btn_class = "btn btn-light";
                                            break;

                                        case 'closed':
                                            $btn_class = "btn btn-danger";
                                            break;

                                        default:
                                            $btn_class = "btn btn-primary";
                                            break;
                                    }
                    ?>
                    <div class="tickets">
                        <div class="ticket-content" style="width:100% !important;">
                            <div class="ticket-header">
                                <div class="ticket-sender-picture img-shadow"><img src="assets/img/avatar/avatar.jpg" alt="image"></div>
                                <div class="ticket-detail">
                                    <div class="ticket-title">
                                        <h4><?php echo $s_disputeHeader; ?></h4>
                                    </div>
                                    <div class="ticket-info">
                                        <div class="font-weight-600 show-bg"><?php echo ucwords(str_replace("-"," ",$s_disputeCategory)); ?></div>
                                        <div class="bullet show-bg"></div>
                                        <div class="font-weight-600"><?php echo $s_disputeEmail; ?></div>
                                        <div class="bullet"></div>
                                        <div class="text-primary font-weight-600"><div class="text-primary"><?php echo TimeAgo($s_time, date("Y-m-d H:i:s")); ?></div></div>
                                    </div>
                                </div>
                            </div>
                            <div class="ticket-description">
                                <p><?php echo $s_disputeMessage; ?></p>
                                <div>
                                    <strong>Status <div class="bullet"></div> <button class="close-d <?php echo $btn_class; ?>" type="button"> <?php echo $s_status;?></button></strong>
                                </div><br>
                                <div id="div-close-dispute">
                                    <form action="" method="post">
                                        <input type="hidden" value="<?php echo $s_disputeId; ?>" name="c_id">
                                        Update Dispute With ID: <strong><?php echo $s_disputeId; ?></strong> to <strong>"Closed"</strong><br><br>
                                        <button class="btn btn-danger" style="float:right;" name="close-dispute-btn"><i class="fa fa-cancel"></i> Close Dispute</button>
                                    </form>
                                </div>
                                <div class="ticket-divider"></div>
                                <div class="ticket-form">
                                    <form action="" method="post">
                                        <div class="form-group">
                                        <input type="hidden" value="<?php echo $s_disputeId; ?>" name="id">
                                        <input type="hidden" value="<?php echo $s_disputeHeader; ?>" name="d_header">
                                        <input type="hidden" value="<?php echo $s_disputeEmail; ?>" name="email">
                                        <textarea class="summernote form-control" placeholder="Type a reply ..." name="reply"></textarea>
                                        </div>
                                        <div class="form-group text-right">
                                        <button class="btn btn-primary btn-lg" id="reply" name="submit">
                                            Reply Dispute
                                        </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php }}else{echo "<script>alert('Error 402! Dispute Id Error.')</script>";}}else{ ?>
                    <div class="col-md-12">
                        <div class="card card-hero">
                            <div class="card-header">
                            <div class="card-icon">
                                <i class="far fa-question-circle"></i>
                            </div>
                            <div class="card-description"><h4><?php echo $disputecount; ?> <span style="font-size:18px !important;">Total Disputes</span></h4></div>
                            </div>
                            <div class="card-body p-0">
                            <div class="tickets-list">
                            <?php
                                if (isset($_GET["active"])) {
                                    $sql = "'active'";
                                }elseif (isset($_GET["open"])) {
                                    $sql = "'open'";
                                }elseif (isset($_GET["closed"])) {
                                    $sql = "'closed'";
                                }else{
                                    $sql = "'open'";
                                }

                                $AllDisputes = "SELECT * FROM _disputes WHERE status = $sql ORDER BY timestamp DESC";
                                $AllDisputesResult = $con->query($AllDisputes);
                                if ($AllDisputesResult -> num_rows > 0) {
                                    while($d_row = mysqli_fetch_array($AllDisputesResult)){
                                        $disputeHeader = $d_row["dispute_header"];
                                        $disputeId = $d_row["dispute_id"];
                                        $disputeEmail = $d_row["dispute_email"];
                                        $time = $d_row["timestamp"];
                            ?>    
                                <a href="disputes?dispute-id=<?php echo crc32($disputeId); ?>" class="ticket-item">
                                    <div class="ticket-title">
                                        <h4><?php echo $disputeHeader; ?></h4>
                                    </div>
                                    <div class="ticket-info">
                                        <div><?php echo $disputeEmail; ?></div>
                                        <div class="bullet"></div>
                                        <div class="text-primary"><?php echo TimeAgo($time, date("Y-m-d H:i:s")); ?></div>
                                    </div>
                                </a>
                            <?php }}else{ ?>
                                <a class="ticket-item">
                                    No <?php echo ucwords(str_replace("'", "", $sql)); ?> Disputes...
                                </a>
                            <?php } ?>
                                
                            </div>
                            </div>
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </section>
        </div>
        
        <!-- Start app Footer part -->
        <?php include '_layout/_footer.php';?>
    </div>
</div>

<!-- General JS Scripts -->
<script src="assets/bundles/lib.vendor.bundle.js"></script>
<script src="js/CodiePie.js"></script>

<!-- JS Libraies -->

<!-- Page Specific JS File -->
<script src="assets/modules/summernote/summernote-bs4.js"></script>
<script src="assets/modules/chocolat/dist/js/jquery.chocolat.min.js"></script>
<script>
    $(".close-d").fireModal({
      title: 'Close Dispute',
      footerClass: 'bg-whitesmoke',
      body: $("#div-close-dispute"),
    });
    /*$("#preiew").fireModal({
      title: 'Mail Preview',
      footerClass: 'bg-whitesmoke',
      body: $("#preiew-tab")
    });

    $("#preview").click(function(){
       // $(".note-editable").html();
        $("#preview-tab").html($(".note-editable").html());
    });*/
    
</script>

<!-- Template JS File -->
<script src="js/scripts.js"></script>
<script src="js/custom.js"></script>
</body>

</html>