<?php
    session_start();
    
    $dbconn = include '_layout/_dbconnection.php';
    if ($dbconn) {}else{ header("Location: 404");}
    
    include '_layout/_time_ago.php';
    

    use PHPMailer\PHPMailer\PHPMailer;
    use PHPMailer\PHPMailer\Exception;
    use PHPMailer\PHPMailer\SMTP;

    if (!isset($_SESSION['admin_loggedin'])) {
        header('Location: sign-in?redirect=order');    
    }

    $messages = [];
    
    if (isset($_POST["update-order-status"])) {
        $upd_order_id = trim(strip_tags($_POST["upd_id"]));
        $upd_order_email = trim(strip_tags($_POST["upd_email"]));
        
        $GetProductsDetails = "SELECT * FROM _users WHERE _email = '$upd_order_id'";
        $ProductsDetailsResult = $con->query($GetProductsDetails);
        if ($ProductsDetailsResult->num_rows > 0) {
            $row = $ProductsDetailsResult->fetch_assoc();
            $lastname = $row["_lastname"];
            $username = $row["_username"];
        }
        if ($lastname != null) {$_usr = $lastname;}else{$_usr = $username;}
        
        $upd_order_status = trim(strip_tags(ucwords($_POST["upd_status"])));
        $Searchps = "SELECT * FROM _allorders WHERE invoice = '$upd_order_id'";
        $SearchpsResult = $con->query($Searchps);
        if ($SearchpsResult -> num_rows > 0) {
            $date = date("F jS, Y");
            # send mail
            require '_mailer/PHPMailer.php';
            require '_mailer/SMTP.php';
            require '_mailer/Exception.php';
                        
            $mail = new PHPMailer();
            $mail->isSMTP();
            $mail->Host = 'mail.tedmaniatv.com'; # prolly use simganic smtp
            $mail->SMTPAuth = true;
            $mail->Username = 'admin@tedmaniatv.com'; # paste one generated by Mailtrap
            $mail->Password = '@lhZkJC_9*p{'; # paste one generated by Mailtrap
            $mail->SMTPSecure = 'ssl';
            $mail->Port = 465;

            $mail->setFrom("info@tedmaniatv.com", "SimGanic");
            $mail->addReplyTo("info@tedmaniatv.com", "SimGanic");
            $mail->addAddress($upd_order_email); # name is optional

            # mail dependencies
            $id = crc32($upd_order_id);
            $page_link = "https://simganic.com/shipped-products?order-id=".$id;
            $pre_link = "https://simganic.com/products/";
            $faq_link = "https://simganic.com/faqs#cancel-order";
            $web = "https://simganic.com/";
            $website = "https://simganic.com/";
            $report_link = "https://simganic.com/report-order?order=".$id;
            $_user_email_address = $upd_order_email;
            

            $mail->Subject = "Status Changed For Order: ".$upd_order_id;

            #include $_SERVER['DOCUMENT_ROOT'].'_layout/_mails.php';

            if ($upd_order_status === "Delivered") {
                $Dismissps = "UPDATE _allorders SET status = '$upd_order_status', delivery_date = '$date' WHERE invoice = '$upd_order_id'";
                # mail continued
                $admin_confirmed_order_delivered_email = '
                    <!DOCTYPE html>
                    <html>
                    <head>
                    </head>
                    <body>
                        <div class="content bg-light" style="color:#563d7c;border: 1px solid #563d7c;padding: 10px;border-radius: 5px;background-color:#DCE1E5 !important;font-family: \'Raleway\', \'Segoe UI\', arial;font-size:15px;">
                            <div class="logo">
                                
                            </div>
                            <div class="content-body" style="background: white;padding: 20px;border-radius: 5px;">
                                ';
                                    # working cos of session start and db connection above
                                    #add dependencies
                                    $GetCartDetails = $SingleOrders = "SELECT * FROM _allorders WHERE crc32(invoice) = '$id' AND email = '$_user_email_address' AND status != 'Closed'";
                                    $GetCartDetailsResult = $con->query($GetCartDetails);
                                    $rowcount = mysqli_num_rows($GetCartDetailsResult);
                                    if ($GetCartDetailsResult->num_rows > 0) {
                                        while ($cartRow = mysqli_fetch_assoc($GetCartDetailsResult)) {
                                            $order_items = $cartRow["items"];
                                            $order_inv = $cartRow["invoice"];
                                            $order_shipping_fee = $cartRow["shipping_fee"];
                                            $order_status = ucwords($cartRow["status"]);
                                            $order_total_price = $cartRow["total_price"];
                                            $order_items = unserialize($order_items);     

                                            include "_layout/_currency_converter.php";
                                            $currency_symbol = $user_selected_currency_symbol;
                                            if ($order_shipping_fee == null) {
                                                $order_shipping_fee = 0;
                                            }
                                $admin_confirmed_order_delivered_email .= '
                                <div class="content-header-text" style="font-weight:700;margin-bottom: 10px;font-size:25px;">Status Changed For Order: '.strtoupper($order_inv).'</div>
                                <hr style="margin-bottom:20px;">
                                <div style="font-size:16px;">
                                    <p style="font-weight:700;font-size:18px;margin-bottom:10px"><strong>Hi '.ucwords($_usr).',</strong></p>
                                    Your order: '.strtoupper($order_inv).' has been confirmed as "Delivered" by our delivery vendor. Click the button below to report or confirm order delivery.
                                </div>
                                <div style="margin-top:30px;margin-bottom:30px;"><a style="text-align: center;box-shadow:0 2px 6px #7a58ad;background-color:#563d7c;border-color:#563d7c;padding: 10px 10px;color:white;text-decoration:none;border-radius:5px;" href="'.$page_link.'" class="btn btn-primary">Confirm Order &raquo;</a></div>
                                <div style="font-weight:700;font-size:17px;margin-bottom:10px;text-decoration:none;">Order Summary :</div>
                                <div class="table-responsie">
                                <table class="table table-striped table-hover table-md" style="width:100%;color:#563d7c;border: 1px solid #563d7c;border-collapse: collapse;">
                                    <tr>
                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;">#</th>
                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:left;">Product(s)</th>
                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:center;">Price</th>
                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:center;">Quantity</th>
                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:right;">Total</th>
                                    </tr>
                                    ';
                                        foreach ($order_items as $key => $value) {
                                            $val = $value['p_id'];
                                            $GetProductDetails = "SELECT * FROM product_details WHERE product_id = '$val'";
                                            $GetProductDetailsResult = $con->query($GetProductDetails);
                                            while ($row = mysqli_fetch_assoc($GetProductDetailsResult)) {
                                                if ($GetProductDetailsResult->num_rows > 0) {
                                                    $name = $row["product_name"];
                                                    $link = $row["product_link"];            
                                    $admin_confirmed_order_delivered_email .= '
                                    <tr>
                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:center;"><strong>#</strong></td>
                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:left;"><a style="text-decoration:none;" href="'.$pre_link.$link.'/">'.$name.' ('.$value['p_size'].')</a></td>
                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:center;">'.$currency_symbol."".$value['p_price'].'</td>
                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:center;">'.$value['p_qty'].'</td>
                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:right;">'.$currency_symbol."".number_format((intval($value['p_price']) * intval($value['p_qty'])), 2).'</td>
                                    </tr>
                                    '; }}} $admin_confirmed_order_delivered_email .= '
                                                    
                                </table>
                                <div class="text-right table-total" style="text-align:right;">
                                    <div style="margin: 10px 0px !important;"><strong>SubTotal :</strong> '.$currency_symbol.'<span class=\'show-bg\'> </span>'.number_format($order_total_price, 2).'</div>
                                    <div><strong>Total (+ Shipping Fee) :</strong> '.$currency_symbol.'<span class=\'show-bg\'> </span>'.number_format(($order_total_price + $order_shipping_fee), 2).'</div>
                                </div>
                                </div>
                                '; }} $admin_confirmed_order_delivered_email .= '
                                <hr style="border-color:transparent;">
                                <div style="margin-top:20px;margin-bottom:20px;">
                                    <strong>NOTICE:</strong> Orders can only be cancelled before they get shipped to get a full refund.<br>
                                </div>
                                <hr>
                                <div class="text-right" style="text-align:right;margin-top:40px;">
                                    <div>Thanks For Shopping With Us,</div>
                                    <a style="text-decoration:none;" href="mailto:support@simganic.com">support@simganic.com</a>
                                    <div class="content-footer">
                                    <a href=""><i class="fa-brands fa-facebook"></i></a> 
                                    <a href=""><i class="fa-brands fa-whatsapp"></i></a> 
                                    <a href=""><i class="fa-brands fa-instagram"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </body>
                    </html>
                '; # send status changed email with confirm order button
                $mail->Body = $admin_confirmed_order_delivered_email;
                $mail->AltBody = 'Your order: '.strtoupper($upd_order_id).' has been Delivered. Check order details page for more information.';
            }elseif ($upd_order_status === "Cancelled") {
                $Dismissps = "UPDATE _allorders SET status = '$upd_order_status', updated_on = '$date' WHERE invoice = '$upd_order_id'";
                # mail continued
                $order_cancelled_email = '
                        <!DOCTYPE html>
                        <html>
                        <head>
                        </head>
                        <body>
                            <div class="content bg-light" style="color:#563d7c;border: 1px solid #563d7c;padding: 10px;border-radius: 5px;background-color:#DCE1E5 !important;font-family: \'Raleway\', \'Segoe UI\', arial;font-size:15px;">
	                            <div class="logo">
	                                
	                            </div>
	                            <div class="content-body" style="background: white;padding: 20px;border-radius: 5px;">
                                    ';
                                        # working cos of session start and db connection above
                                        #add dependencies
                                        $GetCartDetails = $SingleOrders = "SELECT * FROM _allorders WHERE crc32(invoice) = '$id' AND email = '$_user_email_address' AND status != 'Closed'";
                                        $GetCartDetailsResult = $con->query($GetCartDetails);
                                        $rowcount = mysqli_num_rows($GetCartDetailsResult);
                                        if ($GetCartDetailsResult->num_rows > 0) {
                                            while ($cartRow = mysqli_fetch_assoc($GetCartDetailsResult)) {
                                                $order_items = $cartRow["items"];
                                                $order_inv = $cartRow["invoice"];
                                                $order_shipping_fee = $cartRow["shipping_fee"];
                                                $order_status = ucwords($cartRow["status"]);
                                                $order_total_price = $cartRow["total_price"];
                                                $order_items = unserialize($order_items);     

                                                include "_layout/_currency_converter.php";
                                                $currency_symbol = $user_selected_currency_symbol;
                                                if ($order_shipping_fee == null) {
                                                    $order_shipping_fee = 0;
                                                }
                                    $order_cancelled_email .= '
                                    <div class="content-header-text" style="font-weight:700;margin-bottom: 10px;font-size:25px;">Status Changed For Order: '.strtoupper($order_inv).'</div>
                                    <hr style="margin-bottom:20px;">
                                    <div style="font-size:16px;">
                                        <p style="font-weight:700;font-size:18px;margin-bottom:10px"><strong>Hi '.ucwords($_usr).',</strong></p>
                                        Your order: '.strtoupper($order_inv).' has been cancelled because your payment could not be completed. <br>If any amount was debited from your bank account, please mail us @ <a style="text-decoration:none;" href="mailto:support@simganic.com">support@simganic.com</a> providing us with full details of the transaction.
                                    </div>
                                    <div style="margin-top:30px;margin-bottom:30px;"><a href="'.$page_link.'" class="btn btn-primary" style="text-align: center;box-shadow:0 2px 6px #7a58ad;background-color:#563d7c;border-color:#563d7c;padding: 10px 10px;color:white;text-decoration:none;border-radius:5px;">Check Order Details &raquo;</a></div>
                                    <div style="font-weight:700;font-size:17px;margin-bottom:10px;text-decoration:none;">Order Summary :</div>
                                    <div class="table-responsie">
                                    <table class="table table-striped table-hover table-md" style="width:100%;color:#563d7c;border: 1px solid #563d7c;border-collapse: collapse;">
	                                    <tr>
	                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;">#</th>
	                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:left;">Product(s)</th>
	                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:center;">Price</th>
	                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:center;">Quantity</th>
	                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:right;">Total</th>
	                                    </tr>
                                        ';
                                            foreach ($order_items as $key => $value) {
                                                $val = $value['p_id'];
                                                $GetProductDetails = "SELECT * FROM product_details WHERE product_id = '$val'";
                                                $GetProductDetailsResult = $con->query($GetProductDetails);
                                                while ($row = mysqli_fetch_assoc($GetProductDetailsResult)) {
                                                    if ($GetProductDetailsResult->num_rows > 0) {
                                                        $name = $row["product_name"];
                                                        $link = $row["product_link"];            
                                        $order_cancelled_email .= '
                                        <tr>
	                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:center;"><strong>#</strong></td>
	                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:left;"><a style="text-decoration:none;" href="'.$pre_link.$link.'/">'.$name.' ('.$value['p_size'].')</a></td>
	                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:center;">'.$currency_symbol."".$value['p_price'].'</td>
	                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:center;">'.$value['p_qty'].'</td>
	                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:right;">'.$currency_symbol."".number_format((intval($value['p_price']) * intval($value['p_qty'])), 2).'</td>
	                                    </tr>
                                        '; }}}
                                    $order_cancelled_email .= '
                                                        
                                    </table>
                                    <div class="text-right table-total" style="text-align:right;">
                                        <div style="margin: 10px 0px !important;"><strong>SubTotal :</strong> '.$currency_symbol.'<span class=\'show-bg\'> </span>'.number_format($order_total_price, 2).'</div>
                                        <div><strong>Total (+ Shipping Fee) :</strong> '.$currency_symbol.'<span class=\'show-bg\'> </span>'.number_format(($order_total_price + $order_shipping_fee), 2).'</div>
                                    </div>
                                    </div>
                                    '; }} 
                                    $order_cancelled_email .= '
                                    <hr style="margin-top:30px;margin-bottom:10px;">
                                    <div class="text-right" style="text-align:right;">
	                                    <div>Thanks For Shopping With Us,</div>
	                                    <a style="text-decoration:none;" href="mailto:support@simganic.com">support@simganic.com</a>
	                                    <div class="content-footer">
	                                    <a href=""><i class="fa-brands fa-facebook"></i></a> 
	                                    <a href=""><i class="fa-brands fa-whatsapp"></i></a> 
	                                    <a href=""><i class="fa-brands fa-instagram"></i></a>
	                                    </div>
	                                </div>
                                </div>
                            </div>
                        </body>
                        </html>
                '; # order has been cancelled  
                $mail->Body = $order_cancelled_email;
                $mail->AltBody = 'Your order: '.strtoupper($upd_order_id).' has been Cancelled. Check order details page for more information.';
            }elseif ($upd_order_status === "Closed") {
                $Dismissps = "UPDATE _allorders SET status = '$upd_order_status', updated_on = '$date' WHERE invoice = '$upd_order_id'";
                # mail continued
                $admin_confirmed_order_closed_email = '
                        <!DOCTYPE html>
                        <html>
                        <head>
                        </head>
                        <body>
                            <div class="content bg-light" style="color:#563d7c;border: 1px solid #563d7c;padding: 10px;border-radius: 5px;background-color:#DCE1E5 !important;font-family: \'Raleway\', \'Segoe UI\', arial;font-size:15px;">
	                            <div class="logo">
	                                
	                            </div>
	                            <div class="content-body" style="background: white;padding: 20px;border-radius: 5px;">
                                    
                                    ';# working cos of session start and db connection above
                                        #add dependencies
                                        $GetCartDetails = "SELECT * FROM _allorders WHERE crc32(invoice) = '$id' AND email = '$_user_email_address' AND status != 'Closed'";
                                        $GetCartDetailsResult = $con->query($GetCartDetails);
                                        $rowcount = mysqli_num_rows($GetCartDetailsResult);
                                        if ($GetCartDetailsResult->num_rows > 0) {
                                            while ($cartRow = mysqli_fetch_assoc($GetCartDetailsResult)) {
                                                $order_items = $cartRow["items"];
                                                $order_inv = $cartRow["invoice"];
                                                $order_shipping_fee = $cartRow["shipping_fee"];
                                                $order_status = ucwords($cartRow["status"]);
                                                $order_total_price = $cartRow["total_price"];
                                                $order_items = unserialize($order_items);     

                                                include "_layout/_currency_converter.php";
                                                $currency_symbol = $user_selected_currency_symbol;
                                                if ($order_shipping_fee == null) {
                                                    $order_shipping_fee = 0;
                                                }
                                   $admin_confirmed_order_closed_email .= '
                                    <div class="content-header-text" style="font-weight:700;margin-bottom: 10px;font-size:25px;">Status Changed For Order: '.strtoupper($order_inv).'</div>
                                    <hr style="margin-bottom:20px;">
                                    <div style="font-size:16px;">
                                        <p style="font-weight:700;font-size:18px;margin-bottom:10px"><strong>Hi '.ucwords($_usr).',</strong></p>
                                        Your order: '.strtoupper($order_inv).' has been confirmed as "Delivered" by our delivery vendor and hereby closed by our administratives as no complaint nor reports were submitted. Click the button below to view details.
                                    </div>
                                    <div style="margin-top:30px;margin-bottom:30px;"><a style="text-align: center;box-shadow:0 2px 6px #7a58ad;background-color:#563d7c;border-color:#563d7c;padding: 10px 10px;color:white;text-decoration:none;border-radius:5px;" href="'.$page_link.'" class="btn btn-primary">View Details &raquo;</a></div>
                                    <div style="font-weight:700;font-size:17px;margin-bottom:10px;text-decoration:none;">Order Summary :</div>
                                    <div class="table-responsie">
                                    <table class="table table-striped table-hover table-md" style="width:100%;color:#563d7c;border: 1px solid #563d7c;border-collapse: collapse;">
	                                    <tr>
	                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;">#</th>
	                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:left;">Product(s)</th>
	                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:center;">Price</th>
	                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:center;">Quantity</th>
	                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:right;">Total</th>
	                                    </tr>
                                        
                                          ';  
                                            foreach ($order_items as $key => $value) {
                                                $valv = $value['p_id'];
                                                $GetProductDetails = "SELECT * FROM product_details WHERE product_id = '$valv' ";
                                                $GetProductDetailsResult = $con->query($GetProductDetails);
                                                while ($row = mysqli_fetch_assoc($GetProductDetailsResult)) {
                                                    if ($GetProductDetailsResult->num_rows > 0) {
                                                        $name = $row["product_name"];
                                                        $link = $row["product_link"];          
                                         $admin_confirmed_order_closed_email .= '
                                        <tr>
	                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:center;"><strong>#</strong></td>
	                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:left;"><a style="text-decoration:none;" href="'.$pre_link.$link.'/">'.$name.' ('.$value['p_size'].')</a></td>
	                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:center;">'.$currency_symbol."".$value['p_price'].'</td>
	                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:center;">'.$value['p_qty'].'</td>
	                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:right;">'.$currency_symbol."".number_format((intval($value['p_price']) * intval($value['p_qty'])), 2).'</td>
	                                    </tr>
                                        '; }}}
                                        $admin_confirmed_order_closed_email .= '
                                                        
                                    </table>
                                    <div class="text-right table-total" style="text-align:right;">
                                        <div style="margin: 10px 0px !important;"><strong>SubTotal :</strong> '.$currency_symbol."<span class='show-bg'> </span>".number_format($order_total_price, 2).'</div>
                                        <div><strong>Total (+ Shipping Fee) :</strong> '.$currency_symbol."<span class='show-bg'> </span>".number_format(($order_total_price + $order_shipping_fee), 2).'</div>
                                    </div>
                                    </div>
                                    '; }} 
                                    $admin_confirmed_order_closed_email .= '
                                    <hr style="margin-top:30px;margin-bottom:10px;">
                                    <div class="text-right" style="text-align:right;">
	                                    <div>Thanks For Shopping With Us,</div>
	                                    <a style="text-decoration:none;" href="mailto:support@simganic.com">support@simganic.com</a>
	                                    <div class="content-footer">
	                                    <a href=""><i class="fa-brands fa-facebook"></i></a> 
	                                    <a href=""><i class="fa-brands fa-whatsapp"></i></a> 
	                                    <a href=""><i class="fa-brands fa-instagram"></i></a>
	                                    </div>
	                                </div>
                                </div>
                            </div>
                        </body>
                        </html>
                '; # send status changed email with confirm order button
                $mail->Body = $admin_confirmed_order_closed_email;
                $mail->AltBody = 'Your order: '.strtoupper($upd_order_id).' has been confirmed and closed. Check order details page for more information.';
            }elseif ($upd_order_status === "Shipped"){
                $Dismissps = "UPDATE _allorders SET status = '$upd_order_status' WHERE invoice = '$upd_order_id'";
                # mail continued
                $order_shipped_email = '
                        <!DOCTYPE html>
                        <html>
                        <head>
                        </head>
                        <body>
                            <div class="content bg-light" style="color:#563d7c;border: 1px solid #563d7c;padding: 10px;border-radius: 5px;background-color:#DCE1E5 !important;font-family: \'Raleway\', \'Segoe UI\', arial;font-size:15px;">
	                            <div class="logo">
	                                
	                            </div>
	                            <div class="content-body" style="background: white;padding: 20px;border-radius: 5px;">
                                    '; $GetCartDetails = $SingleOrders = "SELECT * FROM _allorders WHERE crc32(invoice) = '$id' AND email = '$_user_email_address' AND status != 'Closed'";
                                        $GetCartDetailsResult = $con->query($GetCartDetails);
                                        $rowcount = mysqli_num_rows($GetCartDetailsResult);
                                        if ($GetCartDetailsResult->num_rows > 0) {
                                            while ($cartRow = mysqli_fetch_assoc($GetCartDetailsResult)) {
                                                $order_items = $cartRow["items"];
                                                $order_inv = $cartRow["invoice"];
                                                $order_shipping_fee = $cartRow["shipping_fee"];
                                                $order_status = ucwords($cartRow["status"]);
                                                $order_total_price = $cartRow["total_price"];
                                                $order_items = unserialize($order_items);     

                                                include "_layout/_currency_converter.php";
                                                $currency_symbol = $user_selected_currency_symbol;
                                                if ($order_shipping_fee == null) {
                                                    $order_shipping_fee = 0;
                                                }
                                    $order_shipped_email .= '
                                    <div class="content-header-text" style="font-weight:700;margin-bottom: 10px;font-size:25px;">Status Changed For Order: '.strtoupper($order_inv).'</div>
                                    <hr style="margin-bottom:20px;">
                                    <div style="font-size:16px;">
                                        <p style="font-weight:700;font-size:18px;margin-bottom:10px"><strong>Hi '.ucwords($_usr).',</strong></p>
                                        Your order: '.strtoupper($order_inv).' has been shipped. Check order details page for more information.
                                    </div>
                                    <div style="margin-top:30px;margin-bottom:30px;"><a style="text-align: center;box-shadow:0 2px 6px #7a58ad;background-color:#563d7c;border-color:#563d7c;padding: 10px 10px;color:white;text-decoration:none;border-radius:5px;" href="'.$page_link.'" class="btn btn-primary">Check Order Details &raquo;</a></div>
                                    <div style="font-weight:700;font-size:17px;margin-bottom:10px;text-decoration:none;">Order Summary :</div>
                                    <div class="table-responsie">
                                    <table class="table table-striped table-hover table-md" style="width:100%;color:#563d7c;border: 1px solid #563d7c;border-collapse: collapse;">
	                                    <tr>
	                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;">#</th>
	                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:left;">Product(s)</th>
	                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:center;">Price</th>
	                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:center;">Quantity</th>
	                                        <th style="padding: 7px;border: 1px solid #563d7c;border-collapse: collapse;text-align:right;">Total</th>
	                                    </tr>
                                        <?php
                                            ';foreach ($order_items as $key => $value) {
                                                $valv = $value['p_id']; # random word
                                                $GetProductDetails = "SELECT * FROM product_details WHERE product_id = '$valv'";
                                                $GetProductDetailsResult = $con->query($GetProductDetails);
                                                while ($row = mysqli_fetch_assoc($GetProductDetailsResult)) {
                                                    if ($GetProductDetailsResult->num_rows > 0) {
                                                        $name = $row["product_name"];
                                                        $link = $row["product_link"];          
                                        $order_shipped_email .= '
                                        <tr>
	                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:center;"><strong>#</strong></td>
	                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:left;"><a style="text-decoration:none;" href="'.$pre_link.$link.'/">'.$name.' ('.$value['p_size'].')</a></td>
	                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:center;">'.$currency_symbol."".$value['p_price'].'</td>
	                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:center;">'.$value['p_qty'].'</td>
	                                        <td style="border: 1px solid #563d7c;border-collapse: collapse;padding:5px;text-align:right;">'.$currency_symbol."".number_format((intval($value['p_price']) * intval($value['p_qty'])), 2).'</td>
	                                    </tr>
                                        '; }}}

                                    $order_shipped_email .= '
                                                        
                                    </table>
                                    <div class="text-right table-total" style="text-align:right;">
                                        <div style="margin: 10px 0px !important;"><strong>SubTotal :</strong> '.$currency_symbol."<span class='show-bg'> </span>".number_format($order_total_price, 2).'</div>
                                        <div><strong>Total (+ Shipping Fee) :</strong> '.$currency_symbol."<span class='show-bg'> </span>".number_format(($order_total_price + $order_shipping_fee), 2).'</div>
                                    </div>
                                    </div>
                                    '; }} 
                                    $order_shipped_email .= '
                                    <hr style="border-color:transparent;">
	                                <div style="margin-top:20px;margin-bottom:20px;">
	                                    <strong>NOTICE:</strong> Orders can only be cancelled before they get shipped to get a full refund.<br>
	                                </div>
                                    <hr>
                                    <div class="text-right" style="text-align:right;margin-top:40px;">
	                                    <div>Thanks For Shopping With Us,</div>
	                                    <a style="text-decoration:none;" href="mailto:support@simganic.com">support@simganic.com</a>
	                                    <div class="content-footer">
	                                    <a href=""><i class="fa-brands fa-facebook"></i></a> 
	                                    <a href=""><i class="fa-brands fa-whatsapp"></i></a> 
	                                    <a href=""><i class="fa-brands fa-instagram"></i></a>
	                                    </div>
	                                </div>
                                </div>
                            </div>
                        </body>
                        </html>
                '; # order has been shipped
                $mail->Body = $order_shipped_email;
                $mail->AltBody = 'Your order: '.strtoupper($upd_order_id).' has been Shipped. Check order details page for more information.';
            }else{
                array_push($messages, "Error 402! Error.");
                exit();
            }
            $DismisspsResult = $con->query($Dismissps);
            if ($DismisspsResult) {
                array_push($messages, "Status Changed For Invoice: ".$upd_order_id." Succesfully.");
                $mail->isHTML(true);
                # $mail->send();
                if($mail->send()){
                    array_push($messages, "Status Update Mail Sent Succesfully.");
                }else{ 
                    array_push($messages, "Error 501! Message could not be sent. Mailer Error: {$mail->ErrorInfo}");
                }
            }else{
                array_push($messages, "Error 401! SQL Error.");
            }
        }else{
            array_push($messages, "Error 402! Order ID Error.");
        }
    }

?>
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
<title>All Customer Order - SimGanic Admin</title>

<!-- General CSS Files -->
<link rel="stylesheet" href="assets/modules/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="assets/modules/fontawesome/css/all.min.css">
<link rel="stylesheet" href="assets/fonts/font-awesome-6/css/all.css">

<!-- CSS Libraries -->

<!-- Template CSS -->
<link rel="stylesheet" href="assets/css/style.min.css">
<link rel="stylesheet" href="assets/css/components.min.css">
<link rel="stylesheet" href="assets/css/mystyle.css">
</head>

<body class="layout-1">
<!-- Page Loader -->
<div class="page-loader-wrapper">
    <span class="loader"><span class="loader-inner"></span></span>
</div>

<div id="app">
    <div class="main-wrapper main-wrapper-1">
        <div class="navbar-bg"></div>
        
        <?php include '_layout/_header_sidebar_admin.php';?>
        
        <!-- Start app main Content -->
        <div class="main-content">
            <section class="section">
                <div class="section-header">
                    <div class="section-header-breadcrumb">
                        <div class="breadcrumb-item active"><a href="/">Home</a></div>
                        <div class="breadcrumb-item">Orders</div>
                    </div>
                </div>

                <div class="section-body">
	                <?php if (count($messages) > 0) : ?>
	                    <div class="alert-div">
	                        <?php foreach ($messages as $error) : ?>
	                        <div class="alert alert-primary alert-dismissible show fade">
	                            <div class="alert-body">
	                                <button class="close" data-dismiss="alert"><span>×</span></button>
	                                <?php echo $error ?>
	                            </div>
	                        </div>
	                        <?php endforeach ?>
	                    </div>
	                <?php endif ?>

	                <?php 
                        if (isset($_GET["order-id"])) {
                            $id = trim(strip_tags($_GET["order-id"]));
                            $SingleOrders = "SELECT * FROM _allorders WHERE crc32(invoice) = '$id'";
                            $SingleOrdersResult = $con->query($SingleOrders);
                            if ($SingleOrdersResult -> num_rows > 0) {
                                while($_row = mysqli_fetch_array($SingleOrdersResult)){
                                    $order_email = $_row["email"];
                                    $order_name = $_row["name"];
                                    $order_items = $_row["items"];
                                    $order_address = $_row["address"];
                                    $order_phone_number = $_row["phone_number"];
                                    $order_total_price = $_row["total_price"];
                                    $order_invoice = $_row["invoice"];
                                    $order_date = $_row["_date"];
                                    $order_time = $_row["_time"];
                                    $order_status = ucwords($_row["status"]);

                                    $order_items = unserialize($order_items);

                                    switch ($order_status) {
                                        case 'Unpaid':
                                            $btn_class = "btn btn-danger";
                                            $updateStatus = "Closed";
                                            break;

                                        case 'Paid':
                                            $btn_class = "btn btn-light";
                                            $updateStatus = "Shipped";
                                            break;

                                        case 'Shipped':
                                            $btn_class = "btn btn-warning";
                                            $updateStatus = "Delivered";
                                            break;

                                        case 'Delivered':
                                            $btn_class = "btn btn-success";
                                            $updateStatus = "Closed";
                                            break;

                                        default:
                                            $btn_class = "btn btn-primary";
                                            $updateStatus = "Shipped";
                                            break;
                                    }

                                    $_user_email_address = $order_email;
                                    include '_layout/_currency_converter.php';
    
    								$currency_symbol = $user_selected_currency_symbol;

                    ?>
                    <div class="col-md-12">
                    	<div class="invoice-title">
                            <h5>INVOICE ID: <span style="font-weight:normal !important;"><?php echo $order_invoice ?></span></h5>
                        </div><hr><br>
                        <address>
                        	<h6>ORDERED ON</h6>
                        	<?php echo $order_date ?>
                        	<div class="bullet"></div>
                        	<?php echo $order_time ?>
                        </address><br>
                        <address>
                            <h6>BILLED TO:</h6>
                            <strong>Name :</strong> <?php echo $order_name;?><div class="bullet show-bg"></div><br class="show-sm">
                            <strong>Email <span class="show-bg">Address</span>:</strong> <?php echo $order_email; ?><div class="bullet show-bg"></div><br class="show-sm">
                            <strong>Phone No :</strong> <?php echo $order_phone_number ; ?>
                        </address><br>
                        <address>
                            <h6>SHIPPED TO:</h6>
                            <?php echo $order_address ;?>
                        </address><br>
                        <div>
                            <strong>Order Status <div class="bullet"></div> <button class="close-d <?php echo $btn_class; ?>" type="button"> <?php echo $order_status;?></button></strong>
                        </div><hr>
                        <h5><i class="fa fa-hashtag"></i> Order Summary</h5><br>
                        <div class="table-responsie">
                            <table class="table table-striped table-hover table-md">
                                <tr>
                                    <th data-width="40">#</th>
                                    <th>Item(s)</th>
                                    <th class="text-center">Price</th>
                                    <th class="text-center">Quantity</th>
                                    <th class="text-right">Total</th>
                                </tr>
                                <?php
                                    foreach ($order_items as $key => $value) {
                                        $GetProductDetails = "SELECT * FROM product_details WHERE product_id = '$value[p_id]'";
                                        $GetProductDetailsResult = $con->query($GetProductDetails);
                                        while ($row = mysqli_fetch_assoc($GetProductDetailsResult)) {
                                            if ($GetProductDetailsResult->num_rows > 0) {
                                                $name = $row["product_name"];            
                                ?>
                                <tr>
                                    <td><strong>#</strong></td>
                                    <td><?php echo $name." (".$value['p_size'].")"; ?></td>
                                    <td class="text-center"><?php echo $currency_symbol."<span class='show-bg'> </span>".$value['p_price']; ?></td>
                                    <td class="text-center"><?php echo $value['p_qty']; ?></td>
                                    <td class="text-right"><?php echo $currency_symbol."<span class='show-bg'> </span>".intval($value['p_price']) * intval($value['p_qty']); ?></td>
                                </tr>
                                <?php }}}?>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td class="text-right"><strong>SubTotal:</strong> <?php echo $currency_symbol.$order_total_price ?></td>
                                </tr>
                            </table>
                        </div>
                        <div id="div-update-order">
                            <form action="" method="post">
                                <input type="hidden" value="<?php echo $order_invoice; ?>" name="upd_id">
                                <input type="hidden" value="<?php echo $updateStatus; ?>" name="upd_status">
                                <input type="hidden" value="<?php echo $order_email; ?>" name="upd_email">
                                Update Order With Invoice ID: <strong><?php echo $order_invoice; ?></strong> to <strong>"<?php echo $updateStatus; ?>"</strong><br><br>
                                <button class="btn btn-danger" style="float:right;" name="update-order-status"><i class="fa fa-cancel"></i> Update Order Status</button>
                            </form>
                        </div>
                    </div>
                    <?php }}else{echo "<script>alert('Error 402! Order Invoice Error.')</script>";}}else{ ?>
                    <div class="col-md-12">
                        <?php

                            if (isset($_GET["shipped"])) {
                                $sql = "status = 'shipped'";
                                $key = "Shipped";
                                $end = "ly";
                            }elseif (isset($_GET["cancelled"])) {
                                $sql = "status = 'cancelled'";
                                $key = "Cancelled";
                                $end = "ly";
                            }elseif (isset($_GET["unpaid"])) {
                                $sql = "status = 'unpaid'";
                                $key = "Unpaid";
                                $end = null;
                            }elseif (isset($_GET["paid"])) {
                                $sql = "status = 'paid'";
                                $key = "Paid";
                                $end = "ly";
                            }else{
                                $sql = "status != 'cancelled' OR status != 'closed'";
                                $key = null;
                                $end = null;
                            }
                        ?>
                        <div class="card">
                            <div class="card-header">
                                <h4>Recent<?php echo $end; ?> <?php echo $key; ?> Order Invoices</h4>
                                <div class="card-header-action">
                                    <a href="" class="btn btn-danger show-bg">View All <i class="fas fa-chevron-right"></i></a>
                                </div>
                            </div>
                            <div class="card-body p-0">
                                <div class="table-responsive table-invoice">
                                    <table class="table table-striped">
                                    <tbody><tr>
                                        <th>Invoice</th>
                                        <th>Customer</th>
                                        <th>Status</th>
                                        <th>Order Date</th>
                                        <th>Action</th>
                                    </tr>
                                    <?php

                                    	$AllOrders = "SELECT * FROM _allorders WHERE $sql ORDER BY _date DESC";
                                        $AllOrdersResult = $con->query($AllOrders);
                                        if ($AllOrdersResult -> num_rows > 0) {
                                            while($row = mysqli_fetch_array($AllOrdersResult)){
                                                $invoice = $row["invoice"];
                                                $name = $row["name"];
                                                //$items = $row["items"];
                                                $date = $row["_date"];
                                                $status = $row["status"];

                                                switch ($status) {
                                                    case 'unpaid':
                                                        $btn_class = "badge-warning";
                                                        break;

                                                    case 'paid':
                                                        $btn_class = "badge-light";
                                                        break;

                                                    case 'shipped':
                                                        $btn_class = "badge-warning";
                                                        break;

                                                    default:
                                                        $btn_class = "badge-primary";
                                                        break;
                                                }
                                    ?>

                                    <tr>
                                        <td><a href="order?order-id=<?php echo crc32($invoice); ?>"><?php echo $invoice; ?></a></td>
                                        <td class="font-weight-600"><?php echo $name; ?></td>
                                        <td><div class="badge <?php echo $btn_class; ?>"><?php echo ucwords($status); ?></div></td>
                                        <td><?php echo $date; ?></td>
                                        <td>
                                        <a href="order?order-id=<?php echo crc32($invoice); ?>" class="btn btn-primary">Details <i class="fas fa-arrow-right"></i></a>
                                        </td>
                                    </tr>

                                    <?php }}else{ ?>
                                       <tr><td><h4>No <?php echo $key; ?> Orders Yet!</h4></td></tr>
                                    <?php } ?>
                                    </tbody></table>
                                    <div style="margin-left:25px;margin-bottom:10px;display:none;">
                                        Showing <strong>1 - 10</strong> of <strong>10</strong> orders <div class="bullet"></div> <a href="#" class="btn btn-danger">View All <i class="fas fa-chevron-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php } ?>
                </div>

            </section>
        </div>

        <!-- Start app Footer part -->
        <?php include '_layout/_footer.php';?>
    </div>
</div>

<!-- General JS Scripts -->
<script src="assets/bundles/lib.vendor.bundle.js"></script>
<script src="js/CodiePie.js"></script>

<!-- JS Libraies -->

<!-- Page Specific JS File -->
<script>
    $(".close-d").fireModal({
      title: 'Update Order Status',
      footerClass: 'bg-whitesmoke',
      body: $("#div-update-order"),
    });
</script>

<!-- Template JS File -->
<script src="js/scripts.js"></script>
<script src="js/custom.js"></script>
</body>

</html>